//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Feature.TrainingForm {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/TrainingForm/TrainingForm template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{32880F2C-C747-4F42-BEE8-790218014D70}", "Diz/8Nqz8nUaGlfk8kiglzxH0jU=", "Valtech.Foundation.Synthesis")]
    public partial interface ITrainingFormItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the HideChildTrainingFormsFromList field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("hidechildtrainingformsfromlist")]
        Synthesis.FieldTypes.Interfaces.IBooleanField HideChildTrainingFormsFromList {
            get;
        }
        
        /// <summary>Represents the HideThisTrainingFormFromList field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("hidethistrainingformfromlist")]
        Synthesis.FieldTypes.Interfaces.IBooleanField HideThisTrainingFormFromList {
            get;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Concrete.Feature.TrainingForm {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/TrainingForm/TrainingForm template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class TrainingForm : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.TrainingForm.ITrainingFormItem {
        
        private Synthesis.FieldTypes.BooleanField _hideChildTrainingFormsFromList;
        
        private Synthesis.FieldTypes.BooleanField _hideThisTrainingFormFromList;
        
        public TrainingForm(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public TrainingForm(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "TrainingForm";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{32880F2C-C747-4F42-BEE8-790218014D70}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the HideChildTrainingFormsFromList field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("hidechildtrainingformsfromlist")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField HideChildTrainingFormsFromList {
            get {
                if (_hideChildTrainingFormsFromList == null) {
                    _hideChildTrainingFormsFromList = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{C43EB9AF-3DD5-4FA3-9BDD-79C083E3C259}"], "/sitecore/templates/Feature/TrainingForm/TrainingForm", "HideChildTrainingFormsFromList"), this.GetSearchFieldValue("hidechildtrainingformsfromlist"));
                }
                return _hideChildTrainingFormsFromList;
            }
        }
        
        /// <summary>Represents the HideThisTrainingFormFromList field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("hidethistrainingformfromlist")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField HideThisTrainingFormFromList {
            get {
                if (_hideThisTrainingFormFromList == null) {
                    _hideThisTrainingFormFromList = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{9A970602-4B3F-4B50-B2F9-1024982D9C3E}"], "/sitecore/templates/Feature/TrainingForm/TrainingForm", "HideThisTrainingFormFromList"), this.GetSearchFieldValue("hidethistrainingformfromlist"));
                }
                return _hideThisTrainingFormFromList;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class TrainingFormInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{32880F2C-C747-4F42-BEE8-790218014D70}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new TrainingForm(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new TrainingForm(searchFields);
        }
    }
}
