//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Project.Friskis.ContentTypes {
    
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/CountryContainer template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{29BBA25B-AABE-405E-9388-84381D582484}", "OtOPB7PSzIc/vFESXKtGCCmmAfQ=", "Valtech.Foundation.Synthesis")]
    public partial interface ICountryContainerItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/DataSourceFolder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{F7B78574-8135-4A79-B5C3-C313ABA1B06E}", "Cl7N8KX6dQzRdXteuIJNKrjILKE=", "Valtech.Foundation.Synthesis")]
    public partial interface IDataSourceFolderItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/PropertyFolder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{42A0D00F-CE10-4139-9D08-BE5854A2158C}", "txFq31ypqk+b9370Nao/tc0EWNI=", "Valtech.Foundation.Synthesis")]
    public partial interface IPropertyFolderItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/SettingsFolder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{A00AC400-2525-4C8E-BDA9-092B3667D233}", "PDks4tuI7tOPVyeV4tBg5lVYvpQ=", "Valtech.Foundation.Synthesis")]
    public partial interface ISettingsFolderItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/VTestComponent template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{D14B2093-D2AE-42CD-924B-4D9E02B6D229}", "M8h/93kBif2UZVgp/60JY6KYDB4=", "Valtech.Foundation.Synthesis")]
    public partial interface IVTestComponentItem : global::FOS.Website.Feature.Content.Data.IVTestComponentItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/WebsiteRoot template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{7184FCA8-1AF5-456F-B3CE-993C68DDE071}", "3+ilLtr4yy6Zrf5GW8Zkwwn+OD8=", "Valtech.Foundation.Synthesis")]
    public partial interface IWebsiteRootItem : global::FOS.Website.Foundation.Dictionary.Data.IDictionarySelectorItem, global::FOS.Website.Foundation.Settings.ISettingsSelectorItem {
    }
}
namespace FOS.Website.Project.Friskis.PageTypes {
    
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/AssociationListPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{9A435B37-877A-4B12-B9EA-6DF7540698DD}", "CZQeE12N2Oru6x9NtRkoePLyV8s=", "Valtech.Foundation.Synthesis")]
    public partial interface IAssociationListPageItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/AssociationPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{ED6742D6-FC75-4FCF-B245-4F89EEF2824D}", "n+FL4A1wY6gfDRyJyHLp/fZYq3U=", "Valtech.Foundation.Synthesis")]
    public partial interface IAssociationPageItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/FTestPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{D86BA794-7B80-4016-91AE-DD43A1EA9695}", "yAjH8Vo9kEhIoMDcRK+QzJxrQU0=", "Valtech.Foundation.Synthesis")]
    public partial interface IFTestPageItem : global::FOS.Website.Feature.Document.Data.IDocumentTitleItem, global::FOS.Website.Feature.Content.Data.IFTestPageItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/Frontpage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{B08553A1-4D24-411A-9AF4-0F076996FF45}", "st5H+gsFtLQPgW4Htzl4O6oVE2Q=", "Valtech.Foundation.Synthesis")]
    public partial interface IFrontpageItem : global::FOS.Website.Feature.Document.Data.IDocumentTitleItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/GymPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{11192A93-2C8B-4C41-8D4F-DB7B3A95B20F}", "sjrxBCKJdQVAkMx8SjRWHMizVCc=", "Valtech.Foundation.Synthesis")]
    public partial interface IGymPageItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/TestPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{C36479A7-B5FB-4212-BC1A-D9822258C333}", "PXN++iY6ipuOIh47tMdUqkI+9Co=", "Valtech.Foundation.Synthesis")]
    public partial interface ITestPageItem : global::FOS.Website.Feature.Document.Data.IDocumentTitleItem, global::FOS.Website.Feature.Content.Data.ITestPageItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/VTestPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{EABD78B9-DAAF-4E64-ABD3-3581AA015D4A}", "ZMnSPFLhGv/1exC7LRodUTJQAzY=", "Valtech.Foundation.Synthesis")]
    public partial interface IVTestPageItem : global::FOS.Website.Feature.Document.Data.IDocumentTitleItem, global::FOS.Website.Feature.Content.Data.IVTestPageItem, global::FOS.Website.Feature.Content.Data.ITeaserItem {
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Concrete.Project.Friskis.ContentTypes {
    
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/CountryContainer template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class CountryContainer : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.ContentTypes.ICountryContainerItem {
        
        public CountryContainer(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public CountryContainer(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "CountryContainer";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{29BBA25B-AABE-405E-9388-84381D582484}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class CountryContainerInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{29BBA25B-AABE-405E-9388-84381D582484}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new CountryContainer(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new CountryContainer(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/DataSourceFolder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class DataSourceFolder : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.ContentTypes.IDataSourceFolderItem {
        
        public DataSourceFolder(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public DataSourceFolder(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "DataSourceFolder";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{F7B78574-8135-4A79-B5C3-C313ABA1B06E}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class DataSourceFolderInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{F7B78574-8135-4A79-B5C3-C313ABA1B06E}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new DataSourceFolder(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new DataSourceFolder(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/PropertyFolder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class PropertyFolder : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.ContentTypes.IPropertyFolderItem {
        
        public PropertyFolder(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public PropertyFolder(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "PropertyFolder";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{42A0D00F-CE10-4139-9D08-BE5854A2158C}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class PropertyFolderInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{42A0D00F-CE10-4139-9D08-BE5854A2158C}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new PropertyFolder(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new PropertyFolder(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/SettingsFolder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class SettingsFolder : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.ContentTypes.ISettingsFolderItem {
        
        public SettingsFolder(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public SettingsFolder(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "SettingsFolder";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{A00AC400-2525-4C8E-BDA9-092B3667D233}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class SettingsFolderInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{A00AC400-2525-4C8E-BDA9-092B3667D233}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new SettingsFolder(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new SettingsFolder(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/VTestComponent template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class VTestComponent : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.ContentTypes.IVTestComponentItem {
        
        private Synthesis.FieldTypes.TextField _heading;
        
        private Synthesis.FieldTypes.ImageField _image;
        
        private Synthesis.FieldTypes.HyperlinkField _link;
        
        public VTestComponent(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public VTestComponent(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "VTestComponent";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{D14B2093-D2AE-42CD-924B-4D9E02B6D229}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("heading")]
        public Synthesis.FieldTypes.Interfaces.ITextField Heading {
            get {
                if (_heading == null) {
                    _heading = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{3C2FEBD0-D0E2-4B62-8899-43CBC51D18C6}"], "/sitecore/templates/Project/Friskis/Content Types/VTestComponent", "Heading"), this.GetSearchFieldValue("heading"));
                }
                return _heading;
            }
        }
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        public Synthesis.FieldTypes.Interfaces.IImageField Image {
            get {
                if (_image == null) {
                    _image = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{4B04AFB6-56EC-45DD-838A-D42BEEF455D4}"], "/sitecore/templates/Project/Friskis/Content Types/VTestComponent", "Image"), this.GetSearchFieldValue("image"));
                }
                return _image;
            }
        }
        
        /// <summary>Represents the Link field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField Link {
            get {
                if (_link == null) {
                    _link = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{207F3A7B-037C-46FD-9D10-74C39A369652}"], "/sitecore/templates/Project/Friskis/Content Types/VTestComponent", "Link"), this.GetSearchFieldValue("link"));
                }
                return _link;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class VTestComponentInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{D14B2093-D2AE-42CD-924B-4D9E02B6D229}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new VTestComponent(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new VTestComponent(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/WebsiteRoot template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class WebsiteRoot : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.ContentTypes.IWebsiteRootItem {
        
        private Synthesis.FieldTypes.ItemReferenceField _dictionary_Dictionary;
        
        private Synthesis.FieldTypes.ItemReferenceField _settings_SettingsRoot;
        
        public WebsiteRoot(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public WebsiteRoot(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "WebsiteRoot";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{7184FCA8-1AF5-456F-B3CE-993C68DDE071}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Dictionary_Dictionary field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("dictionary_dictionary")]
        public Synthesis.FieldTypes.Interfaces.IItemReferenceField Dictionary_Dictionary {
            get {
                if (_dictionary_Dictionary == null) {
                    _dictionary_Dictionary = new Synthesis.FieldTypes.ItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{3EA7D8E1-1A00-482B-AA21-90E701917D33}"], "/sitecore/templates/Project/Friskis/Content Types/WebsiteRoot", "Dictionary_Dictionary"), this.GetSearchFieldValue("dictionary_dictionary"));
                }
                return _dictionary_Dictionary;
            }
        }
        
        /// <summary>Represents the Settings_SettingsRoot field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("settings_settingsroot")]
        public Synthesis.FieldTypes.Interfaces.IItemReferenceField Settings_SettingsRoot {
            get {
                if (_settings_SettingsRoot == null) {
                    _settings_SettingsRoot = new Synthesis.FieldTypes.ItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E0303F65-4DBE-4C82-8F89-64BE2B92FD0F}"], "/sitecore/templates/Project/Friskis/Content Types/WebsiteRoot", "Settings_SettingsRoot"), this.GetSearchFieldValue("settings_settingsroot"));
                }
                return _settings_SettingsRoot;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class WebsiteRootInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{7184FCA8-1AF5-456F-B3CE-993C68DDE071}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new WebsiteRoot(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new WebsiteRoot(searchFields);
        }
    }
}
namespace FOS.Website.Concrete.Project.Friskis.PageTypes {
    
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/AssociationListPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class AssociationListPage : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.PageTypes.IAssociationListPageItem {
        
        public AssociationListPage(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public AssociationListPage(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "AssociationListPage";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{9A435B37-877A-4B12-B9EA-6DF7540698DD}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class AssociationListPageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{9A435B37-877A-4B12-B9EA-6DF7540698DD}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new AssociationListPage(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new AssociationListPage(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/AssociationPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class AssociationPage : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.PageTypes.IAssociationPageItem {
        
        public AssociationPage(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public AssociationPage(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "AssociationPage";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{ED6742D6-FC75-4FCF-B245-4F89EEF2824D}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class AssociationPageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{ED6742D6-FC75-4FCF-B245-4F89EEF2824D}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new AssociationPage(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new AssociationPage(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/FTestPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class FTestPage : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.PageTypes.IFTestPageItem {
        
        private Synthesis.FieldTypes.TextField _document_Title;
        
        private Synthesis.FieldTypes.TextField _testPageText;
        
        private Synthesis.FieldTypes.HyperlinkField _testPageGeneralLink;
        
        private Synthesis.FieldTypes.ImageField _testPageImage;
        
        private Synthesis.FieldTypes.RichTextField _testPageRichText;
        
        private Synthesis.FieldTypes.DateTimeField _testPageDate;
        
        public FTestPage(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public FTestPage(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "FTestPage";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{D86BA794-7B80-4016-91AE-DD43A1EA9695}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Document_Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("document_title")]
        public Synthesis.FieldTypes.Interfaces.ITextField Document_Title {
            get {
                if (_document_Title == null) {
                    _document_Title = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2426E7C6-EE09-4AAA-B2DC-37CE828F7CB4}"], "/sitecore/templates/Project/Friskis/Page Types/FTestPage", "Document_Title"), this.GetSearchFieldValue("document_title"));
                }
                return _document_Title;
            }
        }
        
        /// <summary>Represents the TestPageText field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagetext")]
        public Synthesis.FieldTypes.Interfaces.ITextField TestPageText {
            get {
                if (_testPageText == null) {
                    _testPageText = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{312F8191-461E-4066-A646-DDC25577C13E}"], "/sitecore/templates/Project/Friskis/Page Types/FTestPage", "TestPageText"), this.GetSearchFieldValue("testpagetext"));
                }
                return _testPageText;
            }
        }
        
        /// <summary>Represents the TestPageGeneralLink field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagegenerallink")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField TestPageGeneralLink {
            get {
                if (_testPageGeneralLink == null) {
                    _testPageGeneralLink = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{00C0C211-0BF8-45A6-96FE-8DDBF1F3540B}"], "/sitecore/templates/Project/Friskis/Page Types/FTestPage", "TestPageGeneralLink"), this.GetSearchFieldValue("testpagegenerallink"));
                }
                return _testPageGeneralLink;
            }
        }
        
        /// <summary>Represents the TestPageImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpageimage")]
        public Synthesis.FieldTypes.Interfaces.IImageField TestPageImage {
            get {
                if (_testPageImage == null) {
                    _testPageImage = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{06C37E3F-13F2-40F3-BE96-D5E620DE0FCD}"], "/sitecore/templates/Project/Friskis/Page Types/FTestPage", "TestPageImage"), this.GetSearchFieldValue("testpageimage"));
                }
                return _testPageImage;
            }
        }
        
        /// <summary>Represents the TestPageRichText field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagerichtext")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField TestPageRichText {
            get {
                if (_testPageRichText == null) {
                    _testPageRichText = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{272F4518-FD77-4B7F-A94F-B2B3ED6373A8}"], "/sitecore/templates/Project/Friskis/Page Types/FTestPage", "TestPageRichText"), this.GetSearchFieldValue("testpagerichtext"));
                }
                return _testPageRichText;
            }
        }
        
        /// <summary>Represents the TestPageDate field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagedate")]
        public Synthesis.FieldTypes.Interfaces.IDateTimeField TestPageDate {
            get {
                if (_testPageDate == null) {
                    _testPageDate = new Synthesis.FieldTypes.DateTimeField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{EAF2C39A-919B-4BCB-87C4-55C4B651E26A}"], "/sitecore/templates/Project/Friskis/Page Types/FTestPage", "TestPageDate"), this.GetSearchFieldValue("testpagedate"));
                }
                return _testPageDate;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class FTestPageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{D86BA794-7B80-4016-91AE-DD43A1EA9695}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new FTestPage(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new FTestPage(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/Frontpage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class Frontpage : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.PageTypes.IFrontpageItem {
        
        private Synthesis.FieldTypes.TextField _document_Title;
        
        public Frontpage(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Frontpage(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Frontpage";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{B08553A1-4D24-411A-9AF4-0F076996FF45}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Document_Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("document_title")]
        public Synthesis.FieldTypes.Interfaces.ITextField Document_Title {
            get {
                if (_document_Title == null) {
                    _document_Title = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2426E7C6-EE09-4AAA-B2DC-37CE828F7CB4}"], "/sitecore/templates/Project/Friskis/Page Types/Frontpage", "Document_Title"), this.GetSearchFieldValue("document_title"));
                }
                return _document_Title;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class FrontpageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{B08553A1-4D24-411A-9AF4-0F076996FF45}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Frontpage(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Frontpage(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/GymPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class GymPage : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.PageTypes.IGymPageItem {
        
        public GymPage(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public GymPage(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "GymPage";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{11192A93-2C8B-4C41-8D4F-DB7B3A95B20F}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class GymPageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{11192A93-2C8B-4C41-8D4F-DB7B3A95B20F}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new GymPage(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new GymPage(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/TestPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class TestPage : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.PageTypes.ITestPageItem {
        
        private Synthesis.FieldTypes.TextField _document_Title;
        
        private Synthesis.FieldTypes.TextField _testPageText;
        
        private Synthesis.FieldTypes.HyperlinkField _testPageGeneralLink;
        
        private Synthesis.FieldTypes.ImageField _testPageImage;
        
        private Synthesis.FieldTypes.RichTextField _testPageRichText;
        
        private Synthesis.FieldTypes.DateTimeField _testPageDate;
        
        public TestPage(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public TestPage(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "TestPage";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{C36479A7-B5FB-4212-BC1A-D9822258C333}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Document_Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("document_title")]
        public Synthesis.FieldTypes.Interfaces.ITextField Document_Title {
            get {
                if (_document_Title == null) {
                    _document_Title = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2426E7C6-EE09-4AAA-B2DC-37CE828F7CB4}"], "/sitecore/templates/Project/Friskis/Page Types/TestPage", "Document_Title"), this.GetSearchFieldValue("document_title"));
                }
                return _document_Title;
            }
        }
        
        /// <summary>Represents the TestPageText field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagetext")]
        public Synthesis.FieldTypes.Interfaces.ITextField TestPageText {
            get {
                if (_testPageText == null) {
                    _testPageText = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{36D7705D-3AB1-4CF8-8B9E-3F6FF616DBA1}"], "/sitecore/templates/Project/Friskis/Page Types/TestPage", "TestPageText"), this.GetSearchFieldValue("testpagetext"));
                }
                return _testPageText;
            }
        }
        
        /// <summary>Represents the TestPageGeneralLink field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagegenerallink")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField TestPageGeneralLink {
            get {
                if (_testPageGeneralLink == null) {
                    _testPageGeneralLink = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{83EE949F-0888-4539-948F-329980D8095C}"], "/sitecore/templates/Project/Friskis/Page Types/TestPage", "TestPageGeneralLink"), this.GetSearchFieldValue("testpagegenerallink"));
                }
                return _testPageGeneralLink;
            }
        }
        
        /// <summary>Represents the TestPageImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpageimage")]
        public Synthesis.FieldTypes.Interfaces.IImageField TestPageImage {
            get {
                if (_testPageImage == null) {
                    _testPageImage = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{3319C755-FC9E-4984-8DEE-3EB691293821}"], "/sitecore/templates/Project/Friskis/Page Types/TestPage", "TestPageImage"), this.GetSearchFieldValue("testpageimage"));
                }
                return _testPageImage;
            }
        }
        
        /// <summary>Represents the TestPageRichText field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagerichtext")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField TestPageRichText {
            get {
                if (_testPageRichText == null) {
                    _testPageRichText = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{95BFEE1E-2B9F-4729-BF85-2AB5F82E6777}"], "/sitecore/templates/Project/Friskis/Page Types/TestPage", "TestPageRichText"), this.GetSearchFieldValue("testpagerichtext"));
                }
                return _testPageRichText;
            }
        }
        
        /// <summary>Represents the TestPageDate field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagedate")]
        public Synthesis.FieldTypes.Interfaces.IDateTimeField TestPageDate {
            get {
                if (_testPageDate == null) {
                    _testPageDate = new Synthesis.FieldTypes.DateTimeField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{7092C2C2-6AF6-46C7-826B-40D34A536CBA}"], "/sitecore/templates/Project/Friskis/Page Types/TestPage", "TestPageDate"), this.GetSearchFieldValue("testpagedate"));
                }
                return _testPageDate;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class TestPageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{C36479A7-B5FB-4212-BC1A-D9822258C333}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new TestPage(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new TestPage(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/VTestPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class VTestPage : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.PageTypes.IVTestPageItem {
        
        private Synthesis.FieldTypes.TextField _content_TeaserTextBold;
        
        private Synthesis.FieldTypes.TextField _document_Title;
        
        private Synthesis.FieldTypes.TextField _testPageText;
        
        private Synthesis.FieldTypes.TextField _content_TeaserTextNormal;
        
        private Synthesis.FieldTypes.HyperlinkField _testPageGeneralLink;
        
        private Synthesis.FieldTypes.HyperlinkField _content_TeaserLink;
        
        private Synthesis.FieldTypes.ImageField _testPageImage;
        
        private Synthesis.FieldTypes.RichTextField _testPageRichText;
        
        private Synthesis.FieldTypes.DateTimeField _testPageDate;
        
        private Synthesis.FieldTypes.TextField _testPageExtraText;
        
        public VTestPage(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public VTestPage(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "VTestPage";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{EABD78B9-DAAF-4E64-ABD3-3581AA015D4A}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Content_TeaserTextBold field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("content_teasertextbold")]
        public Synthesis.FieldTypes.Interfaces.ITextField Content_TeaserTextBold {
            get {
                if (_content_TeaserTextBold == null) {
                    _content_TeaserTextBold = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{347444A6-CA4C-4327-9CAC-76277E22BDE0}"], "/sitecore/templates/Project/Friskis/Page Types/VTestPage", "Content_TeaserTextBold"), this.GetSearchFieldValue("content_teasertextbold"));
                }
                return _content_TeaserTextBold;
            }
        }
        
        /// <summary>Represents the Document_Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("document_title")]
        public Synthesis.FieldTypes.Interfaces.ITextField Document_Title {
            get {
                if (_document_Title == null) {
                    _document_Title = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2426E7C6-EE09-4AAA-B2DC-37CE828F7CB4}"], "/sitecore/templates/Project/Friskis/Page Types/VTestPage", "Document_Title"), this.GetSearchFieldValue("document_title"));
                }
                return _document_Title;
            }
        }
        
        /// <summary>Represents the TestPageText field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagetext")]
        public Synthesis.FieldTypes.Interfaces.ITextField TestPageText {
            get {
                if (_testPageText == null) {
                    _testPageText = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{69C5D4B0-DB15-49E6-8094-EA24EE9D9BB7}"], "/sitecore/templates/Project/Friskis/Page Types/VTestPage", "TestPageText"), this.GetSearchFieldValue("testpagetext"));
                }
                return _testPageText;
            }
        }
        
        /// <summary>Represents the Content_TeaserTextNormal field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("content_teasertextnormal")]
        public Synthesis.FieldTypes.Interfaces.ITextField Content_TeaserTextNormal {
            get {
                if (_content_TeaserTextNormal == null) {
                    _content_TeaserTextNormal = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{872493C7-209A-45A7-A4C5-5ED4F44875FF}"], "/sitecore/templates/Project/Friskis/Page Types/VTestPage", "Content_TeaserTextNormal"), this.GetSearchFieldValue("content_teasertextnormal"));
                }
                return _content_TeaserTextNormal;
            }
        }
        
        /// <summary>Represents the TestPageGeneralLink field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagegenerallink")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField TestPageGeneralLink {
            get {
                if (_testPageGeneralLink == null) {
                    _testPageGeneralLink = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{101DBFB5-A1BF-4EFC-B9FB-DAC71C668247}"], "/sitecore/templates/Project/Friskis/Page Types/VTestPage", "TestPageGeneralLink"), this.GetSearchFieldValue("testpagegenerallink"));
                }
                return _testPageGeneralLink;
            }
        }
        
        /// <summary>Represents the Content_TeaserLink field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("content_teaserlink")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField Content_TeaserLink {
            get {
                if (_content_TeaserLink == null) {
                    _content_TeaserLink = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{160B08F0-B317-4862-B0D4-AAA2DB0DCC77}"], "/sitecore/templates/Project/Friskis/Page Types/VTestPage", "Content_TeaserLink"), this.GetSearchFieldValue("content_teaserlink"));
                }
                return _content_TeaserLink;
            }
        }
        
        /// <summary>Represents the TestPageImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpageimage")]
        public Synthesis.FieldTypes.Interfaces.IImageField TestPageImage {
            get {
                if (_testPageImage == null) {
                    _testPageImage = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E2B047F6-9A06-455E-8830-4FFF7C720E4A}"], "/sitecore/templates/Project/Friskis/Page Types/VTestPage", "TestPageImage"), this.GetSearchFieldValue("testpageimage"));
                }
                return _testPageImage;
            }
        }
        
        /// <summary>Represents the TestPageRichText field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagerichtext")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField TestPageRichText {
            get {
                if (_testPageRichText == null) {
                    _testPageRichText = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{26226867-72DF-46D3-9EDD-B780AC89F3A1}"], "/sitecore/templates/Project/Friskis/Page Types/VTestPage", "TestPageRichText"), this.GetSearchFieldValue("testpagerichtext"));
                }
                return _testPageRichText;
            }
        }
        
        /// <summary>Represents the TestPageDate field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagedate")]
        public Synthesis.FieldTypes.Interfaces.IDateTimeField TestPageDate {
            get {
                if (_testPageDate == null) {
                    _testPageDate = new Synthesis.FieldTypes.DateTimeField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{A61AE873-7F28-42CA-A039-12F59EDFD5D2}"], "/sitecore/templates/Project/Friskis/Page Types/VTestPage", "TestPageDate"), this.GetSearchFieldValue("testpagedate"));
                }
                return _testPageDate;
            }
        }
        
        /// <summary>Represents the TestPageExtraText field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpageextratext")]
        public Synthesis.FieldTypes.Interfaces.ITextField TestPageExtraText {
            get {
                if (_testPageExtraText == null) {
                    _testPageExtraText = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{367C100F-2EE5-42D2-AE86-472570C8D28E}"], "/sitecore/templates/Project/Friskis/Page Types/VTestPage", "TestPageExtraText"), this.GetSearchFieldValue("testpageextratext"));
                }
                return _testPageExtraText;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class VTestPageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{EABD78B9-DAAF-4E64-ABD3-3581AA015D4A}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new VTestPage(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new VTestPage(searchFields);
        }
    }
}
