//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Project.Friskis.ContentTypes {
    
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/DataSourceFolder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{F7B78574-8135-4A79-B5C3-C313ABA1B06E}", "Cl7N8KX6dQzRdXteuIJNKrjILKE=", "Valtech.Foundation.Synthesis")]
    public partial interface IDataSourceFolderItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/SettingsFolder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{A00AC400-2525-4C8E-BDA9-092B3667D233}", "PDks4tuI7tOPVyeV4tBg5lVYvpQ=", "Valtech.Foundation.Synthesis")]
    public partial interface ISettingsFolderItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/WebsiteRoot template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{7184FCA8-1AF5-456F-B3CE-993C68DDE071}", "3+ilLtr4yy6Zrf5GW8Zkwwn+OD8=", "Valtech.Foundation.Synthesis")]
    public partial interface IWebsiteRootItem : global::FOS.Website.Foundation.Dictionary.Data.IDictionarySelectorItem, global::FOS.Website.Foundation.Settings.ISettingsSelectorItem {
    }
}
namespace FOS.Website.Project.Friskis.PageTypes {
    
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/FTestPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{D86BA794-7B80-4016-91AE-DD43A1EA9695}", "yAjH8Vo9kEhIoMDcRK+QzJxrQU0=", "Valtech.Foundation.Synthesis")]
    public partial interface IFTestPageItem : global::FOS.Website.Feature.Document.Data.IDocumentTitleItem, global::FOS.Website.Feature.Content.Data.IFTestPageItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/Frontpage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{B08553A1-4D24-411A-9AF4-0F076996FF45}", "st5H+gsFtLQPgW4Htzl4O6oVE2Q=", "Valtech.Foundation.Synthesis")]
    public partial interface IFrontpageItem : global::FOS.Website.Feature.Document.Data.IDocumentTitleItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/TestPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{C36479A7-B5FB-4212-BC1A-D9822258C333}", "PXN++iY6ipuOIh47tMdUqkI+9Co=", "Valtech.Foundation.Synthesis")]
    public partial interface ITestPageItem : global::FOS.Website.Feature.Document.Data.IDocumentTitleItem, global::FOS.Website.Feature.Content.Data.ITestPageItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/VTestPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{EABD78B9-DAAF-4E64-ABD3-3581AA015D4A}", "ZMnSPFLhGv/1exC7LRodUTJQAzY=", "Valtech.Foundation.Synthesis")]
    public partial interface IVTestPageItem : global::FOS.Website.Feature.Document.Data.IDocumentTitleItem, global::FOS.Website.Feature.Content.Data.IVTestPageItem {
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Concrete.Project.Friskis.ContentTypes {
    
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/DataSourceFolder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class DataSourceFolder : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.ContentTypes.IDataSourceFolderItem {
        
        public DataSourceFolder(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public DataSourceFolder(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "DataSourceFolder";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{F7B78574-8135-4A79-B5C3-C313ABA1B06E}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class DataSourceFolderInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{F7B78574-8135-4A79-B5C3-C313ABA1B06E}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new DataSourceFolder(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new DataSourceFolder(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/SettingsFolder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class SettingsFolder : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.ContentTypes.ISettingsFolderItem {
        
        public SettingsFolder(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public SettingsFolder(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "SettingsFolder";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{A00AC400-2525-4C8E-BDA9-092B3667D233}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class SettingsFolderInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{A00AC400-2525-4C8E-BDA9-092B3667D233}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new SettingsFolder(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new SettingsFolder(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Content Types/WebsiteRoot template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class WebsiteRoot : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.ContentTypes.IWebsiteRootItem {
        
        private Synthesis.FieldTypes.ItemReferenceField _dictionary_Dictionary;
        
        private Synthesis.FieldTypes.ItemReferenceField _settings_SettingsRoot;
        
        public WebsiteRoot(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public WebsiteRoot(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "WebsiteRoot";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{7184FCA8-1AF5-456F-B3CE-993C68DDE071}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Dictionary_Dictionary field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("dictionary_dictionary")]
        public Synthesis.FieldTypes.Interfaces.IItemReferenceField Dictionary_Dictionary {
            get {
                if (_dictionary_Dictionary == null) {
                    _dictionary_Dictionary = new Synthesis.FieldTypes.ItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{3EA7D8E1-1A00-482B-AA21-90E701917D33}"], "/sitecore/templates/Project/Friskis/Content Types/WebsiteRoot", "Dictionary_Dictionary"), this.GetSearchFieldValue("dictionary_dictionary"));
                }
                return _dictionary_Dictionary;
            }
        }
        
        /// <summary>Represents the Settings_SettingsRoot field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("settings_settingsroot")]
        public Synthesis.FieldTypes.Interfaces.IItemReferenceField Settings_SettingsRoot {
            get {
                if (_settings_SettingsRoot == null) {
                    _settings_SettingsRoot = new Synthesis.FieldTypes.ItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E0303F65-4DBE-4C82-8F89-64BE2B92FD0F}"], "/sitecore/templates/Project/Friskis/Content Types/WebsiteRoot", "Settings_SettingsRoot"), this.GetSearchFieldValue("settings_settingsroot"));
                }
                return _settings_SettingsRoot;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class WebsiteRootInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{7184FCA8-1AF5-456F-B3CE-993C68DDE071}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new WebsiteRoot(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new WebsiteRoot(searchFields);
        }
    }
}
namespace FOS.Website.Concrete.Project.Friskis.PageTypes {
    
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/FTestPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class FTestPage : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.PageTypes.IFTestPageItem {
        
        private Synthesis.FieldTypes.TextField _document_Title;
        
        private Synthesis.FieldTypes.TextField _testPageText;
        
        private Synthesis.FieldTypes.HyperlinkField _testPageGeneralLink;
        
        private Synthesis.FieldTypes.ImageField _testPageImage;
        
        private Synthesis.FieldTypes.RichTextField _testPageRichText;
        
        private Synthesis.FieldTypes.DateTimeField _testPageDate;
        
        public FTestPage(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public FTestPage(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "FTestPage";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{D86BA794-7B80-4016-91AE-DD43A1EA9695}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Document_Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("document_title")]
        public Synthesis.FieldTypes.Interfaces.ITextField Document_Title {
            get {
                if (_document_Title == null) {
                    _document_Title = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2426E7C6-EE09-4AAA-B2DC-37CE828F7CB4}"], "/sitecore/templates/Project/Friskis/Page Types/FTestPage", "Document_Title"), this.GetSearchFieldValue("document_title"));
                }
                return _document_Title;
            }
        }
        
        /// <summary>Represents the TestPageText field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagetext")]
        public Synthesis.FieldTypes.Interfaces.ITextField TestPageText {
            get {
                if (_testPageText == null) {
                    _testPageText = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{312F8191-461E-4066-A646-DDC25577C13E}"], "/sitecore/templates/Project/Friskis/Page Types/FTestPage", "TestPageText"), this.GetSearchFieldValue("testpagetext"));
                }
                return _testPageText;
            }
        }
        
        /// <summary>Represents the TestPageGeneralLink field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagegenerallink")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField TestPageGeneralLink {
            get {
                if (_testPageGeneralLink == null) {
                    _testPageGeneralLink = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{00C0C211-0BF8-45A6-96FE-8DDBF1F3540B}"], "/sitecore/templates/Project/Friskis/Page Types/FTestPage", "TestPageGeneralLink"), this.GetSearchFieldValue("testpagegenerallink"));
                }
                return _testPageGeneralLink;
            }
        }
        
        /// <summary>Represents the TestPageImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpageimage")]
        public Synthesis.FieldTypes.Interfaces.IImageField TestPageImage {
            get {
                if (_testPageImage == null) {
                    _testPageImage = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{06C37E3F-13F2-40F3-BE96-D5E620DE0FCD}"], "/sitecore/templates/Project/Friskis/Page Types/FTestPage", "TestPageImage"), this.GetSearchFieldValue("testpageimage"));
                }
                return _testPageImage;
            }
        }
        
        /// <summary>Represents the TestPageRichText field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagerichtext")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField TestPageRichText {
            get {
                if (_testPageRichText == null) {
                    _testPageRichText = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{272F4518-FD77-4B7F-A94F-B2B3ED6373A8}"], "/sitecore/templates/Project/Friskis/Page Types/FTestPage", "TestPageRichText"), this.GetSearchFieldValue("testpagerichtext"));
                }
                return _testPageRichText;
            }
        }
        
        /// <summary>Represents the TestPageDate field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagedate")]
        public Synthesis.FieldTypes.Interfaces.IDateTimeField TestPageDate {
            get {
                if (_testPageDate == null) {
                    _testPageDate = new Synthesis.FieldTypes.DateTimeField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{EAF2C39A-919B-4BCB-87C4-55C4B651E26A}"], "/sitecore/templates/Project/Friskis/Page Types/FTestPage", "TestPageDate"), this.GetSearchFieldValue("testpagedate"));
                }
                return _testPageDate;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class FTestPageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{D86BA794-7B80-4016-91AE-DD43A1EA9695}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new FTestPage(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new FTestPage(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/Frontpage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class Frontpage : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.PageTypes.IFrontpageItem {
        
        private Synthesis.FieldTypes.TextField _document_Title;
        
        public Frontpage(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Frontpage(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Frontpage";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{B08553A1-4D24-411A-9AF4-0F076996FF45}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Document_Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("document_title")]
        public Synthesis.FieldTypes.Interfaces.ITextField Document_Title {
            get {
                if (_document_Title == null) {
                    _document_Title = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2426E7C6-EE09-4AAA-B2DC-37CE828F7CB4}"], "/sitecore/templates/Project/Friskis/Page Types/Frontpage", "Document_Title"), this.GetSearchFieldValue("document_title"));
                }
                return _document_Title;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class FrontpageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{B08553A1-4D24-411A-9AF4-0F076996FF45}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Frontpage(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Frontpage(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/TestPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class TestPage : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.PageTypes.ITestPageItem {
        
        private Synthesis.FieldTypes.TextField _document_Title;
        
        private Synthesis.FieldTypes.TextField _testPageText;
        
        private Synthesis.FieldTypes.HyperlinkField _testPageGeneralLink;
        
        private Synthesis.FieldTypes.ImageField _testPageImage;
        
        private Synthesis.FieldTypes.RichTextField _testPageRichText;
        
        private Synthesis.FieldTypes.DateTimeField _testPageDate;
        
        public TestPage(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public TestPage(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "TestPage";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{C36479A7-B5FB-4212-BC1A-D9822258C333}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Document_Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("document_title")]
        public Synthesis.FieldTypes.Interfaces.ITextField Document_Title {
            get {
                if (_document_Title == null) {
                    _document_Title = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2426E7C6-EE09-4AAA-B2DC-37CE828F7CB4}"], "/sitecore/templates/Project/Friskis/Page Types/TestPage", "Document_Title"), this.GetSearchFieldValue("document_title"));
                }
                return _document_Title;
            }
        }
        
        /// <summary>Represents the TestPageText field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagetext")]
        public Synthesis.FieldTypes.Interfaces.ITextField TestPageText {
            get {
                if (_testPageText == null) {
                    _testPageText = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{36D7705D-3AB1-4CF8-8B9E-3F6FF616DBA1}"], "/sitecore/templates/Project/Friskis/Page Types/TestPage", "TestPageText"), this.GetSearchFieldValue("testpagetext"));
                }
                return _testPageText;
            }
        }
        
        /// <summary>Represents the TestPageGeneralLink field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagegenerallink")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField TestPageGeneralLink {
            get {
                if (_testPageGeneralLink == null) {
                    _testPageGeneralLink = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{83EE949F-0888-4539-948F-329980D8095C}"], "/sitecore/templates/Project/Friskis/Page Types/TestPage", "TestPageGeneralLink"), this.GetSearchFieldValue("testpagegenerallink"));
                }
                return _testPageGeneralLink;
            }
        }
        
        /// <summary>Represents the TestPageImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpageimage")]
        public Synthesis.FieldTypes.Interfaces.IImageField TestPageImage {
            get {
                if (_testPageImage == null) {
                    _testPageImage = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{3319C755-FC9E-4984-8DEE-3EB691293821}"], "/sitecore/templates/Project/Friskis/Page Types/TestPage", "TestPageImage"), this.GetSearchFieldValue("testpageimage"));
                }
                return _testPageImage;
            }
        }
        
        /// <summary>Represents the TestPageRichText field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagerichtext")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField TestPageRichText {
            get {
                if (_testPageRichText == null) {
                    _testPageRichText = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{95BFEE1E-2B9F-4729-BF85-2AB5F82E6777}"], "/sitecore/templates/Project/Friskis/Page Types/TestPage", "TestPageRichText"), this.GetSearchFieldValue("testpagerichtext"));
                }
                return _testPageRichText;
            }
        }
        
        /// <summary>Represents the TestPageDate field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagedate")]
        public Synthesis.FieldTypes.Interfaces.IDateTimeField TestPageDate {
            get {
                if (_testPageDate == null) {
                    _testPageDate = new Synthesis.FieldTypes.DateTimeField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{7092C2C2-6AF6-46C7-826B-40D34A536CBA}"], "/sitecore/templates/Project/Friskis/Page Types/TestPage", "TestPageDate"), this.GetSearchFieldValue("testpagedate"));
                }
                return _testPageDate;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class TestPageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{C36479A7-B5FB-4212-BC1A-D9822258C333}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new TestPage(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new TestPage(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Project/Friskis/Page Types/VTestPage template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class VTestPage : global::Synthesis.StandardTemplateItem, global::FOS.Website.Project.Friskis.PageTypes.IVTestPageItem {
        
        private Synthesis.FieldTypes.TextField _document_Title;
        
        private Synthesis.FieldTypes.TextField _testPageText;
        
        private Synthesis.FieldTypes.HyperlinkField _testPageGeneralLink;
        
        private Synthesis.FieldTypes.ImageField _testPageImage;
        
        private Synthesis.FieldTypes.RichTextField _testPageRichText;
        
        private Synthesis.FieldTypes.DateTimeField _testPageDate;
        
        public VTestPage(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public VTestPage(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "VTestPage";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{EABD78B9-DAAF-4E64-ABD3-3581AA015D4A}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Document_Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("document_title")]
        public Synthesis.FieldTypes.Interfaces.ITextField Document_Title {
            get {
                if (_document_Title == null) {
                    _document_Title = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2426E7C6-EE09-4AAA-B2DC-37CE828F7CB4}"], "/sitecore/templates/Project/Friskis/Page Types/VTestPage", "Document_Title"), this.GetSearchFieldValue("document_title"));
                }
                return _document_Title;
            }
        }
        
        /// <summary>Represents the TestPageText field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagetext")]
        public Synthesis.FieldTypes.Interfaces.ITextField TestPageText {
            get {
                if (_testPageText == null) {
                    _testPageText = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{69C5D4B0-DB15-49E6-8094-EA24EE9D9BB7}"], "/sitecore/templates/Project/Friskis/Page Types/VTestPage", "TestPageText"), this.GetSearchFieldValue("testpagetext"));
                }
                return _testPageText;
            }
        }
        
        /// <summary>Represents the TestPageGeneralLink field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagegenerallink")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField TestPageGeneralLink {
            get {
                if (_testPageGeneralLink == null) {
                    _testPageGeneralLink = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{101DBFB5-A1BF-4EFC-B9FB-DAC71C668247}"], "/sitecore/templates/Project/Friskis/Page Types/VTestPage", "TestPageGeneralLink"), this.GetSearchFieldValue("testpagegenerallink"));
                }
                return _testPageGeneralLink;
            }
        }
        
        /// <summary>Represents the TestPageImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpageimage")]
        public Synthesis.FieldTypes.Interfaces.IImageField TestPageImage {
            get {
                if (_testPageImage == null) {
                    _testPageImage = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E2B047F6-9A06-455E-8830-4FFF7C720E4A}"], "/sitecore/templates/Project/Friskis/Page Types/VTestPage", "TestPageImage"), this.GetSearchFieldValue("testpageimage"));
                }
                return _testPageImage;
            }
        }
        
        /// <summary>Represents the TestPageRichText field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagerichtext")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField TestPageRichText {
            get {
                if (_testPageRichText == null) {
                    _testPageRichText = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{26226867-72DF-46D3-9EDD-B780AC89F3A1}"], "/sitecore/templates/Project/Friskis/Page Types/VTestPage", "TestPageRichText"), this.GetSearchFieldValue("testpagerichtext"));
                }
                return _testPageRichText;
            }
        }
        
        /// <summary>Represents the TestPageDate field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("testpagedate")]
        public Synthesis.FieldTypes.Interfaces.IDateTimeField TestPageDate {
            get {
                if (_testPageDate == null) {
                    _testPageDate = new Synthesis.FieldTypes.DateTimeField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{A61AE873-7F28-42CA-A039-12F59EDFD5D2}"], "/sitecore/templates/Project/Friskis/Page Types/VTestPage", "TestPageDate"), this.GetSearchFieldValue("testpagedate"));
                }
                return _testPageDate;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class VTestPageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{EABD78B9-DAAF-4E64-ABD3-3581AA015D4A}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new VTestPage(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new VTestPage(searchFields);
        }
    }
}
