//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Foundation.Dictionary {
    
    
    /// <summary>Represents the /sitecore/templates/Foundation/Dictionary/DictionaryElement template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{DCD7E3CE-9633-4329-981D-D485803063C3}", "hL8wk1SVWetRgYKnljW8bMtMTk0=", "Valtech.Foundation.Synthesis")]
    public partial interface IDictionaryElementItem : global::FOS.Website.Foundation.Dictionary.Data.IDictionaryTextItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/Dictionary/DictionaryFolder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{B7558438-A5E3-49E0-A70E-E0F1DD2B769D}", "BNs8UZfvfu3dd2zuuaSBw+Z/oiY=", "Valtech.Foundation.Synthesis")]
    public partial interface IDictionaryFolderItem : Synthesis.IStandardTemplateItem {
    }
}
namespace FOS.Website.Foundation.Dictionary.Data {
    
    
    /// <summary>Represents the /sitecore/templates/Foundation/Dictionary/Data/DictionarySelector template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{3DCB8703-5653-459B-A81F-4CF83F30BB22}", "LjZVaPYZuqDAP38cV18wvFjBiHQ=", "Valtech.Foundation.Synthesis")]
    public partial interface IDictionarySelectorItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Dictionary_Dictionary field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("dictionary_dictionary")]
        Synthesis.FieldTypes.Interfaces.IItemReferenceField Dictionary_Dictionary {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/Dictionary/Data/DictionaryText template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{530327F4-B598-4819-B3FD-0FF0ECCC7E86}", "box1JldAddbyKsAOJe69W7Rc/+Q=", "Valtech.Foundation.Synthesis")]
    public partial interface IDictionaryTextItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Dictionary_Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("dictionary_text")]
        Synthesis.FieldTypes.Interfaces.ITextField Dictionary_Text {
            get;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Concrete.Foundation.Dictionary {
    
    
    /// <summary>Represents the /sitecore/templates/Foundation/Dictionary/DictionaryElement template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class DictionaryElement : global::Synthesis.StandardTemplateItem, global::FOS.Website.Foundation.Dictionary.IDictionaryElementItem {
        
        private Synthesis.FieldTypes.TextField _dictionary_Text;
        
        public DictionaryElement(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public DictionaryElement(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "DictionaryElement";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{DCD7E3CE-9633-4329-981D-D485803063C3}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Dictionary_Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("dictionary_text")]
        public Synthesis.FieldTypes.Interfaces.ITextField Dictionary_Text {
            get {
                if (_dictionary_Text == null) {
                    _dictionary_Text = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{120431E7-D871-4372-8AA5-69A98BB4FBF4}"], "/sitecore/templates/Foundation/Dictionary/DictionaryElement", "Dictionary_Text"), this.GetSearchFieldValue("dictionary_text"));
                }
                return _dictionary_Text;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class DictionaryElementInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{DCD7E3CE-9633-4329-981D-D485803063C3}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new DictionaryElement(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new DictionaryElement(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/Dictionary/DictionaryFolder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class DictionaryFolder : global::Synthesis.StandardTemplateItem, global::FOS.Website.Foundation.Dictionary.IDictionaryFolderItem {
        
        public DictionaryFolder(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public DictionaryFolder(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "DictionaryFolder";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{B7558438-A5E3-49E0-A70E-E0F1DD2B769D}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class DictionaryFolderInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{B7558438-A5E3-49E0-A70E-E0F1DD2B769D}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new DictionaryFolder(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new DictionaryFolder(searchFields);
        }
    }
}
namespace FOS.Website.Concrete.Foundation.Dictionary.Data {
    
    
    /// <summary>Represents the /sitecore/templates/Foundation/Dictionary/Data/DictionarySelector template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class DictionarySelector : global::Synthesis.StandardTemplateItem, global::FOS.Website.Foundation.Dictionary.Data.IDictionarySelectorItem {
        
        private Synthesis.FieldTypes.ItemReferenceField _dictionary_Dictionary;
        
        public DictionarySelector(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public DictionarySelector(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "DictionarySelector";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{3DCB8703-5653-459B-A81F-4CF83F30BB22}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Dictionary_Dictionary field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("dictionary_dictionary")]
        public Synthesis.FieldTypes.Interfaces.IItemReferenceField Dictionary_Dictionary {
            get {
                if (_dictionary_Dictionary == null) {
                    _dictionary_Dictionary = new Synthesis.FieldTypes.ItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{3EA7D8E1-1A00-482B-AA21-90E701917D33}"], "/sitecore/templates/Foundation/Dictionary/Data/DictionarySelector", "Dictionary_Dictionary"), this.GetSearchFieldValue("dictionary_dictionary"));
                }
                return _dictionary_Dictionary;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class DictionarySelectorInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{3DCB8703-5653-459B-A81F-4CF83F30BB22}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new DictionarySelector(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new DictionarySelector(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Foundation/Dictionary/Data/DictionaryText template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class DictionaryText : global::Synthesis.StandardTemplateItem, global::FOS.Website.Foundation.Dictionary.Data.IDictionaryTextItem {
        
        private Synthesis.FieldTypes.TextField _dictionary_Text;
        
        public DictionaryText(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public DictionaryText(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "DictionaryText";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{530327F4-B598-4819-B3FD-0FF0ECCC7E86}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Dictionary_Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("dictionary_text")]
        public Synthesis.FieldTypes.Interfaces.ITextField Dictionary_Text {
            get {
                if (_dictionary_Text == null) {
                    _dictionary_Text = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{120431E7-D871-4372-8AA5-69A98BB4FBF4}"], "/sitecore/templates/Foundation/Dictionary/Data/DictionaryText", "Dictionary_Text"), this.GetSearchFieldValue("dictionary_text"));
                }
                return _dictionary_Text;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class DictionaryTextInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{530327F4-B598-4819-B3FD-0FF0ECCC7E86}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new DictionaryText(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new DictionaryText(searchFields);
        }
    }
}
