//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Feature.Event {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Event/Event template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{79F96712-0EC9-45A0-A7DA-C34276CBA9AB}", "BCBdYlPTguFKIQkmU0hM9Ib6UmQ=", "Valtech.Foundation.Synthesis")]
    public partial interface IEventItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the EventLocation field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("eventlocation")]
        Synthesis.FieldTypes.Interfaces.ITextField EventLocation {
            get;
        }
        
        /// <summary>Represents the EventStartDate field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("eventstartdate")]
        Synthesis.FieldTypes.Interfaces.IDateTimeField EventStartDate {
            get;
        }
        
        /// <summary>Represents the EventEndDate field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("eventenddate")]
        Synthesis.FieldTypes.Interfaces.IDateTimeField EventEndDate {
            get;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Concrete.Feature.Event {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Event/Event template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class Event : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.Event.IEventItem {
        
        private Synthesis.FieldTypes.TextField _eventLocation;
        
        private Synthesis.FieldTypes.DateTimeField _eventStartDate;
        
        private Synthesis.FieldTypes.DateTimeField _eventEndDate;
        
        public Event(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Event(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Event";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{79F96712-0EC9-45A0-A7DA-C34276CBA9AB}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the EventLocation field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("eventlocation")]
        public Synthesis.FieldTypes.Interfaces.ITextField EventLocation {
            get {
                if (_eventLocation == null) {
                    _eventLocation = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{283303B8-0EBA-4812-9FA2-1A17B29878C4}"], "/sitecore/templates/Feature/Event/Event", "EventLocation"), this.GetSearchFieldValue("eventlocation"));
                }
                return _eventLocation;
            }
        }
        
        /// <summary>Represents the EventStartDate field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("eventstartdate")]
        public Synthesis.FieldTypes.Interfaces.IDateTimeField EventStartDate {
            get {
                if (_eventStartDate == null) {
                    _eventStartDate = new Synthesis.FieldTypes.DateTimeField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{3E870A09-7EBD-4E44-9591-34D7E82ED893}"], "/sitecore/templates/Feature/Event/Event", "EventStartDate"), this.GetSearchFieldValue("eventstartdate"));
                }
                return _eventStartDate;
            }
        }
        
        /// <summary>Represents the EventEndDate field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("eventenddate")]
        public Synthesis.FieldTypes.Interfaces.IDateTimeField EventEndDate {
            get {
                if (_eventEndDate == null) {
                    _eventEndDate = new Synthesis.FieldTypes.DateTimeField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{53815C96-A807-4D4E-9CFF-33E9DE3CDBAA}"], "/sitecore/templates/Feature/Event/Event", "EventEndDate"), this.GetSearchFieldValue("eventenddate"));
                }
                return _eventEndDate;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class EventInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{79F96712-0EC9-45A0-A7DA-C34276CBA9AB}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Event(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Event(searchFields);
        }
    }
}
