//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Feature.Document.Data {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Document/Data/DocumentAbstract template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{3364652B-9368-4E2A-BF67-2374B3C73270}", "nrrnadTtnDr0WZ25cbaVgl1Wuz4=", "Valtech.Foundation.Synthesis")]
    public partial interface IDocumentAbstractItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Document_Abstract field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("document_abstract")]
        Synthesis.FieldTypes.Interfaces.ITextField Document_Abstract {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Document/Data/DocumentTitle template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{0464E715-F96A-4A85-9100-FC8B85A65494}", "durfytvpqtQV+dSZckqcdUYjJKQ=", "Valtech.Foundation.Synthesis")]
    public partial interface IDocumentTitleItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Document_Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("document_title")]
        Synthesis.FieldTypes.Interfaces.ITextField Document_Title {
            get;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Concrete.Feature.Document.Data {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Document/Data/DocumentAbstract template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class DocumentAbstract : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.Document.Data.IDocumentAbstractItem {
        
        private Synthesis.FieldTypes.TextField _document_Abstract;
        
        public DocumentAbstract(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public DocumentAbstract(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "DocumentAbstract";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{3364652B-9368-4E2A-BF67-2374B3C73270}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Document_Abstract field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("document_abstract")]
        public Synthesis.FieldTypes.Interfaces.ITextField Document_Abstract {
            get {
                if (_document_Abstract == null) {
                    _document_Abstract = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{D2F1D0C0-0AD8-457D-BFD0-34B1C5E317EB}"], "/sitecore/templates/Feature/Document/Data/DocumentAbstract", "Document_Abstract"), this.GetSearchFieldValue("document_abstract"));
                }
                return _document_Abstract;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class DocumentAbstractInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{3364652B-9368-4E2A-BF67-2374B3C73270}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new DocumentAbstract(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new DocumentAbstract(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Document/Data/DocumentTitle template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class DocumentTitle : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.Document.Data.IDocumentTitleItem {
        
        private Synthesis.FieldTypes.TextField _document_Title;
        
        public DocumentTitle(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public DocumentTitle(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "DocumentTitle";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{0464E715-F96A-4A85-9100-FC8B85A65494}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Document_Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("document_title")]
        public Synthesis.FieldTypes.Interfaces.ITextField Document_Title {
            get {
                if (_document_Title == null) {
                    _document_Title = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2426E7C6-EE09-4AAA-B2DC-37CE828F7CB4}"], "/sitecore/templates/Feature/Document/Data/DocumentTitle", "Document_Title"), this.GetSearchFieldValue("document_title"));
                }
                return _document_Title;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class DocumentTitleInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{0464E715-F96A-4A85-9100-FC8B85A65494}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new DocumentTitle(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new DocumentTitle(searchFields);
        }
    }
}
