//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Feature.Navigation.Data {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Data/NavigationBarRoot template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{695108BE-03A4-4177-AEF7-3A92F30C48AE}", "TYZm3qwNXByuVa4S+ylr/GABTgc=", "Valtech.Foundation.Synthesis")]
    public partial interface INavigationBarRootItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the BookingLink field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("bookinglink")]
        Synthesis.FieldTypes.Interfaces.IHyperlinkField BookingLink {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Data/NavigationData template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{A2B8D74F-1F5A-4A8D-BB21-599CBC277098}", "i0d6PaNeV1bRoqud4wh7YzljVcI=", "Valtech.Foundation.Synthesis")]
    public partial interface INavigationDataItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Navigation_NavigationTitle field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("navigation_navigationtitle")]
        Synthesis.FieldTypes.Interfaces.ITextField Navigation_NavigationTitle {
            get;
        }
        
        /// <summary>Represents the Navigation_ShowInMenu field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("navigation_showinmenu")]
        Synthesis.FieldTypes.Interfaces.IBooleanField Navigation_ShowInMenu {
            get;
        }
        
        /// <summary>Represents the Navigation_IsSecondary field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("navigation_issecondary")]
        Synthesis.FieldTypes.Interfaces.IBooleanField Navigation_IsSecondary {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Data/Navigation Footer Links Association template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{DF386FEF-1DB8-41BD-88A3-0DAE41FE5453}", "LkQ6rdvQsCZBhLxRdAMaMgRN3ks=", "Valtech.Foundation.Synthesis")]
    public partial interface INavigationFooterLinksAssociationItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Become A Member field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("become_a_member")]
        Synthesis.FieldTypes.Interfaces.IHyperlinkField BecomeAMember {
            get;
        }
        
        /// <summary>Represents the Become A Funkis field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("become_a_funkis")]
        Synthesis.FieldTypes.Interfaces.IHyperlinkField BecomeAFunkis {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Data/NavigationRootPageFlag template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{AB6CD7A3-2AED-4E4A-8E2A-A17C04C395AC}", "7O3T+EwqYxH4lqI8NEI3nwzno28=", "Valtech.Foundation.Synthesis")]
    public partial interface INavigationRootPageFlagItem : Synthesis.IStandardTemplateItem {
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Concrete.Feature.Navigation.Data {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Data/NavigationBarRoot template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class NavigationBarRoot : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.Navigation.Data.INavigationBarRootItem {
        
        private Synthesis.FieldTypes.HyperlinkField _bookingLink;
        
        public NavigationBarRoot(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public NavigationBarRoot(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "NavigationBarRoot";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{695108BE-03A4-4177-AEF7-3A92F30C48AE}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the BookingLink field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("bookinglink")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField BookingLink {
            get {
                if (_bookingLink == null) {
                    _bookingLink = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{A26B0801-FAED-4426-8F97-4D06670FFBEF}"], "/sitecore/templates/Feature/Navigation/Data/NavigationBarRoot", "BookingLink"), this.GetSearchFieldValue("bookinglink"));
                }
                return _bookingLink;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class NavigationBarRootInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{695108BE-03A4-4177-AEF7-3A92F30C48AE}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new NavigationBarRoot(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new NavigationBarRoot(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Data/NavigationData template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class NavigationData : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.Navigation.Data.INavigationDataItem {
        
        private Synthesis.FieldTypes.TextField _navigation_NavigationTitle;
        
        private Synthesis.FieldTypes.BooleanField _navigation_ShowInMenu;
        
        private Synthesis.FieldTypes.BooleanField _navigation_IsSecondary;
        
        public NavigationData(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public NavigationData(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "NavigationData";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{A2B8D74F-1F5A-4A8D-BB21-599CBC277098}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Navigation_NavigationTitle field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("navigation_navigationtitle")]
        public Synthesis.FieldTypes.Interfaces.ITextField Navigation_NavigationTitle {
            get {
                if (_navigation_NavigationTitle == null) {
                    _navigation_NavigationTitle = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{0E12FF8A-DC4F-43F0-8D43-6C2BE8CF4021}"], "/sitecore/templates/Feature/Navigation/Data/NavigationData", "Navigation_NavigationTitle"), this.GetSearchFieldValue("navigation_navigationtitle"));
                }
                return _navigation_NavigationTitle;
            }
        }
        
        /// <summary>Represents the Navigation_ShowInMenu field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("navigation_showinmenu")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField Navigation_ShowInMenu {
            get {
                if (_navigation_ShowInMenu == null) {
                    _navigation_ShowInMenu = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{F60E9BBE-8B37-4EB3-A293-A072E18C67D5}"], "/sitecore/templates/Feature/Navigation/Data/NavigationData", "Navigation_ShowInMenu"), this.GetSearchFieldValue("navigation_showinmenu"));
                }
                return _navigation_ShowInMenu;
            }
        }
        
        /// <summary>Represents the Navigation_IsSecondary field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("navigation_issecondary")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField Navigation_IsSecondary {
            get {
                if (_navigation_IsSecondary == null) {
                    _navigation_IsSecondary = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{5C94595C-5289-4053-911B-C89E461920F4}"], "/sitecore/templates/Feature/Navigation/Data/NavigationData", "Navigation_IsSecondary"), this.GetSearchFieldValue("navigation_issecondary"));
                }
                return _navigation_IsSecondary;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class NavigationDataInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{A2B8D74F-1F5A-4A8D-BB21-599CBC277098}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new NavigationData(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new NavigationData(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Data/Navigation Footer Links Association template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class NavigationFooterLinksAssociation : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.Navigation.Data.INavigationFooterLinksAssociationItem {
        
        private Synthesis.FieldTypes.HyperlinkField _becomeAMember;
        
        private Synthesis.FieldTypes.HyperlinkField _becomeAFunkis;
        
        public NavigationFooterLinksAssociation(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public NavigationFooterLinksAssociation(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Navigation Footer Links Association";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{DF386FEF-1DB8-41BD-88A3-0DAE41FE5453}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Become A Member field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("become_a_member")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField BecomeAMember {
            get {
                if (_becomeAMember == null) {
                    _becomeAMember = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{4947E29E-797A-47B7-9F5D-7EF88933FD92}"], "/sitecore/templates/Feature/Navigation/Data/Navigation Footer Links Association", "Become A Member"), this.GetSearchFieldValue("become_a_member"));
                }
                return _becomeAMember;
            }
        }
        
        /// <summary>Represents the Become A Funkis field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("become_a_funkis")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField BecomeAFunkis {
            get {
                if (_becomeAFunkis == null) {
                    _becomeAFunkis = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{EBC14A33-8C87-4597-B1ED-31478BB0E15B}"], "/sitecore/templates/Feature/Navigation/Data/Navigation Footer Links Association", "Become A Funkis"), this.GetSearchFieldValue("become_a_funkis"));
                }
                return _becomeAFunkis;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class NavigationFooterLinksAssociationInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{DF386FEF-1DB8-41BD-88A3-0DAE41FE5453}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new NavigationFooterLinksAssociation(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new NavigationFooterLinksAssociation(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/Navigation/Data/NavigationRootPageFlag template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class NavigationRootPageFlag : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.Navigation.Data.INavigationRootPageFlagItem {
        
        public NavigationRootPageFlag(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public NavigationRootPageFlag(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "NavigationRootPageFlag";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{AB6CD7A3-2AED-4E4A-8E2A-A17C04C395AC}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class NavigationRootPageFlagInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{AB6CD7A3-2AED-4E4A-8E2A-A17C04C395AC}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new NavigationRootPageFlag(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new NavigationRootPageFlag(searchFields);
        }
    }
}
