//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Feature.ComponentBlock {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/ComponentBlock/ComponentBlockContent template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{D058483A-3EDE-4E30-AF91-BA4612187F42}", "SptbCa7wwiS043tk/ijXr+woZtw=", "Valtech.Foundation.Synthesis")]
    public partial interface IComponentBlockContentItem : Synthesis.IStandardTemplateItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ComponentBlock/ComponentBlock template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{339D2673-0907-4136-A6E8-4EEF5E682353}", "1N6h7I2ie1/yCeX+nqfsqpv6QC8=", "Valtech.Foundation.Synthesis")]
    public partial interface IComponentBlockItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the ComponentBlockItem field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("componentblockitem")]
        Synthesis.FieldTypes.Interfaces.IItemReferenceField ComponentBlockItem {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ComponentBlock/OriginalItem template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{C6532DDF-ADD9-4E1A-8CF0-780648DBEDDE}", "yGK8pHrxlP4gP15yTrT13wwuMqg=", "Valtech.Foundation.Synthesis")]
    public partial interface IOriginalItemItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the OriginalItemLink field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("originalitemlink")]
        Synthesis.FieldTypes.Interfaces.IItemReferenceField OriginalItemLink {
            get;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Concrete.Feature.ComponentBlock {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/ComponentBlock/ComponentBlock template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class ComponentBlock : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ComponentBlock.IComponentBlockItem {
        
        private Synthesis.FieldTypes.ItemReferenceField _componentBlockItem;
        
        public ComponentBlock(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public ComponentBlock(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "ComponentBlock";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{339D2673-0907-4136-A6E8-4EEF5E682353}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the ComponentBlockItem field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("componentblockitem")]
        public Synthesis.FieldTypes.Interfaces.IItemReferenceField ComponentBlockItem {
            get {
                if (_componentBlockItem == null) {
                    _componentBlockItem = new Synthesis.FieldTypes.ItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{6ED9E5BF-0FCC-4AEB-ADAD-125C508AE31A}"], "/sitecore/templates/Feature/ComponentBlock/ComponentBlock", "ComponentBlockItem"), this.GetSearchFieldValue("componentblockitem"));
                }
                return _componentBlockItem;
            }
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ComponentBlock/ComponentBlockContent template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class ComponentBlockContent : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ComponentBlock.IComponentBlockContentItem {
        
        public ComponentBlockContent(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public ComponentBlockContent(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "ComponentBlockContent";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{D058483A-3EDE-4E30-AF91-BA4612187F42}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class ComponentBlockContentInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{D058483A-3EDE-4E30-AF91-BA4612187F42}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new ComponentBlockContent(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new ComponentBlockContent(searchFields);
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class ComponentBlockInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{339D2673-0907-4136-A6E8-4EEF5E682353}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new ComponentBlock(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new ComponentBlock(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ComponentBlock/OriginalItem template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class OriginalItem : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ComponentBlock.IOriginalItemItem {
        
        private Synthesis.FieldTypes.ItemReferenceField _originalItemLink;
        
        public OriginalItem(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public OriginalItem(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "OriginalItem";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{C6532DDF-ADD9-4E1A-8CF0-780648DBEDDE}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the OriginalItemLink field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("originalitemlink")]
        public Synthesis.FieldTypes.Interfaces.IItemReferenceField OriginalItemLink {
            get {
                if (_originalItemLink == null) {
                    _originalItemLink = new Synthesis.FieldTypes.ItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{F1C13FFB-740B-4951-B4F4-393A81791013}"], "/sitecore/templates/Feature/ComponentBlock/OriginalItem", "OriginalItemLink"), this.GetSearchFieldValue("originalitemlink"));
                }
                return _originalItemLink;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class OriginalItemInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{C6532DDF-ADD9-4E1A-8CF0-780648DBEDDE}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new OriginalItem(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new OriginalItem(searchFields);
        }
    }
}
