//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Common {
    
    
    /// <summary>Represents the /sitecore/templates/Common/Folder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{A87A00B1-E6DB-45AB-8B54-636FEC3B5523}", "Zt0+eHcT7w8sdyKxEekhqBiTmA4=", "Valtech.Foundation.Synthesis")]
    public partial interface IFolderItem : Synthesis.IStandardTemplateItem {
    }
}
namespace FOS.Website.Feature.CustomScripts.Data {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/CustomScripts/Data/BaseScript template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{67178892-42C1-4374-803C-3065A43D1DD7}", "yLOAqjyy4Wy6hN8ociwlPNAh6Ew=", "Valtech.Foundation.Synthesis")]
    public partial interface IBaseScriptItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the CustomScripts field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("customscripts")]
        Synthesis.FieldTypes.Interfaces.ITextField CustomScripts {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/CustomScripts/Data/GlobalCustomScript template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{38F6251A-C832-491A-9484-3A4280D0F123}", "eI6e4LY6SZGMu30/3RBrgXLW9rE=", "Valtech.Foundation.Synthesis")]
    public partial interface IGlobalCustomScriptItem : global::FOS.Website.Feature.CustomScripts.Data.IBaseScriptItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/CustomScripts/Data/GlobalCustomScriptsSettingsFolder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{4D355206-90C2-4F1F-99D8-2BD7E2689255}", "iJQURhNjEc17MUlGTISCrRWIkVY=", "Valtech.Foundation.Synthesis")]
    public partial interface IGlobalCustomScriptsSettingsFolderItem : global::FOS.Website.Common.IFolderItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/CustomScripts/Data/PageSpecificCustomScripts template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{602AD6D7-64FD-4C48-BB41-DFA04638CCAD}", "+ZkQARREWucB5KveIUrf0CbdfuQ=", "Valtech.Foundation.Synthesis")]
    public partial interface IPageSpecificCustomScriptsItem : global::FOS.Website.Feature.CustomScripts.Data.IBaseScriptItem {
        
        /// <summary>Represents the ScriptsInheritedOnSubpages field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("scriptsinheritedonsubpages")]
        Synthesis.FieldTypes.Interfaces.ITextField ScriptsInheritedOnSubpages {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/CustomScripts/Data/SiteCustomScriptsSettingsFolder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{6C6B74C9-03DB-4CF2-85B8-41F79A067FF5}", "d+95Yw+A5FAIqQ8D5cxCQD+y3zM=", "Valtech.Foundation.Synthesis")]
    public partial interface ISiteCustomScriptsSettingsFolderItem : global::FOS.Website.Common.IFolderItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/CustomScripts/Data/SiteSpecificScript template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{4FE6B6B9-1608-4D3A-BB3D-B0D3C1D36694}", "oH4O5BvcXsA4wZ43OPHFXOJkTYg=", "Valtech.Foundation.Synthesis")]
    public partial interface ISiteSpecificScriptItem : global::FOS.Website.Feature.CustomScripts.Data.IBaseScriptItem {
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Concrete.Feature.CustomScripts.Data {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/CustomScripts/Data/BaseScript template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class BaseScript : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.CustomScripts.Data.IBaseScriptItem {
        
        private Synthesis.FieldTypes.TextField _customScripts;
        
        public BaseScript(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public BaseScript(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "BaseScript";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{67178892-42C1-4374-803C-3065A43D1DD7}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the CustomScripts field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("customscripts")]
        public Synthesis.FieldTypes.Interfaces.ITextField CustomScripts {
            get {
                if (_customScripts == null) {
                    _customScripts = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{30627248-3125-4A7E-BF76-DECFAD8FB7AB}"], "/sitecore/templates/Feature/CustomScripts/Data/BaseScript", "CustomScripts"), this.GetSearchFieldValue("customscripts"));
                }
                return _customScripts;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class BaseScriptInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{67178892-42C1-4374-803C-3065A43D1DD7}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new BaseScript(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new BaseScript(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/CustomScripts/Data/GlobalCustomScript template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class GlobalCustomScript : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.CustomScripts.Data.IGlobalCustomScriptItem {
        
        private Synthesis.FieldTypes.TextField _customScripts;
        
        public GlobalCustomScript(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public GlobalCustomScript(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "GlobalCustomScript";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{38F6251A-C832-491A-9484-3A4280D0F123}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the CustomScripts field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("customscripts")]
        public Synthesis.FieldTypes.Interfaces.ITextField CustomScripts {
            get {
                if (_customScripts == null) {
                    _customScripts = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{30627248-3125-4A7E-BF76-DECFAD8FB7AB}"], "/sitecore/templates/Feature/CustomScripts/Data/GlobalCustomScript", "CustomScripts"), this.GetSearchFieldValue("customscripts"));
                }
                return _customScripts;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class GlobalCustomScriptInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{38F6251A-C832-491A-9484-3A4280D0F123}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new GlobalCustomScript(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new GlobalCustomScript(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/CustomScripts/Data/GlobalCustomScriptsSettingsFolder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class GlobalCustomScriptsSettingsFolder : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.CustomScripts.Data.IGlobalCustomScriptsSettingsFolderItem {
        
        public GlobalCustomScriptsSettingsFolder(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public GlobalCustomScriptsSettingsFolder(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "GlobalCustomScriptsSettingsFolder";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{4D355206-90C2-4F1F-99D8-2BD7E2689255}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class GlobalCustomScriptsSettingsFolderInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{4D355206-90C2-4F1F-99D8-2BD7E2689255}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new GlobalCustomScriptsSettingsFolder(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new GlobalCustomScriptsSettingsFolder(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/CustomScripts/Data/PageSpecificCustomScripts template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class PageSpecificCustomScripts : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.CustomScripts.Data.IPageSpecificCustomScriptsItem {
        
        private Synthesis.FieldTypes.TextField _customScripts;
        
        private Synthesis.FieldTypes.TextField _scriptsInheritedOnSubpages;
        
        public PageSpecificCustomScripts(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public PageSpecificCustomScripts(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "PageSpecificCustomScripts";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{602AD6D7-64FD-4C48-BB41-DFA04638CCAD}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the CustomScripts field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("customscripts")]
        public Synthesis.FieldTypes.Interfaces.ITextField CustomScripts {
            get {
                if (_customScripts == null) {
                    _customScripts = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{30627248-3125-4A7E-BF76-DECFAD8FB7AB}"], "/sitecore/templates/Feature/CustomScripts/Data/PageSpecificCustomScripts", "CustomScripts"), this.GetSearchFieldValue("customscripts"));
                }
                return _customScripts;
            }
        }
        
        /// <summary>Represents the ScriptsInheritedOnSubpages field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("scriptsinheritedonsubpages")]
        public Synthesis.FieldTypes.Interfaces.ITextField ScriptsInheritedOnSubpages {
            get {
                if (_scriptsInheritedOnSubpages == null) {
                    _scriptsInheritedOnSubpages = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{F64D4477-A514-4BF8-8539-B9FF7B2F9F36}"], "/sitecore/templates/Feature/CustomScripts/Data/PageSpecificCustomScripts", "ScriptsInheritedOnSubpages"), this.GetSearchFieldValue("scriptsinheritedonsubpages"));
                }
                return _scriptsInheritedOnSubpages;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class PageSpecificCustomScriptsInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{602AD6D7-64FD-4C48-BB41-DFA04638CCAD}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new PageSpecificCustomScripts(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new PageSpecificCustomScripts(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/CustomScripts/Data/SiteCustomScriptsSettingsFolder template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class SiteCustomScriptsSettingsFolder : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.CustomScripts.Data.ISiteCustomScriptsSettingsFolderItem {
        
        public SiteCustomScriptsSettingsFolder(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public SiteCustomScriptsSettingsFolder(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "SiteCustomScriptsSettingsFolder";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{6C6B74C9-03DB-4CF2-85B8-41F79A067FF5}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class SiteCustomScriptsSettingsFolderInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{6C6B74C9-03DB-4CF2-85B8-41F79A067FF5}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new SiteCustomScriptsSettingsFolder(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new SiteCustomScriptsSettingsFolder(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/CustomScripts/Data/SiteSpecificScript template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class SiteSpecificScript : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.CustomScripts.Data.ISiteSpecificScriptItem {
        
        private Synthesis.FieldTypes.TextField _customScripts;
        
        public SiteSpecificScript(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public SiteSpecificScript(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "SiteSpecificScript";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{4FE6B6B9-1608-4D3A-BB3D-B0D3C1D36694}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the CustomScripts field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("customscripts")]
        public Synthesis.FieldTypes.Interfaces.ITextField CustomScripts {
            get {
                if (_customScripts == null) {
                    _customScripts = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{30627248-3125-4A7E-BF76-DECFAD8FB7AB}"], "/sitecore/templates/Feature/CustomScripts/Data/SiteSpecificScript", "CustomScripts"), this.GetSearchFieldValue("customscripts"));
                }
                return _customScripts;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class SiteSpecificScriptInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{4FE6B6B9-1608-4D3A-BB3D-B0D3C1D36694}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new SiteSpecificScript(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new SiteSpecificScript(searchFields);
        }
    }
}
