//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Feature.ContentBlocks.Blocks {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndText template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{21EA2408-A9D6-4CA6-AFD1-80798B77B5DB}", "Um+KleS1XIdbPymarUQx7Y6AiCQ=", "Valtech.Foundation.Synthesis")]
    public partial interface IImageAndTextItem : global::FOS.Website.Feature.ContentBlocks.Data.IHeadingItem, global::FOS.Website.Feature.ContentBlocks.Data.IImageItem, global::FOS.Website.Feature.ContentBlocks.Data.IRichTextItem {
        
        /// <summary>Represents the InvertPositions field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("invertpositions")]
        Synthesis.FieldTypes.Interfaces.IBooleanField InvertPositions {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Blocks/Manual Link CTA template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{AB4BCE34-FFF4-4045-AB94-6D05A7E95468}", "KN1SMvNfluL4CXXZk51WM8Pa/PY=", "Valtech.Foundation.Synthesis")]
    public partial interface IManualLinkCTAItem : global::FOS.Website.Feature.ContentBlocks.Data.IHeadingItem, global::FOS.Website.Feature.ContentBlocks.Data.ILinkItem, global::FOS.Website.Feature.ContentBlocks.Data.IImageItem {
    }
}
namespace FOS.Website.Feature.ContentBlocks.Data {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Heading template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{2F8D1730-8E48-4D2A-AC96-4547DD5CDC02}", "FcOSvfGM2nzMXd1mzYjMV8wY/Sk=", "Valtech.Foundation.Synthesis")]
    public partial interface IHeadingItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("heading")]
        Synthesis.FieldTypes.Interfaces.ITextField Heading1 {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Image template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{76F41557-F22A-4CFB-95E7-B3D9D1781FAC}", "ANLZ27SJAlExNxsS2heCIgRQ5Og=", "Valtech.Foundation.Synthesis")]
    public partial interface IImageItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        Synthesis.FieldTypes.Interfaces.IImageField Image1 {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Link template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{FA69C4B3-2B4A-4A48-89E7-8430DE6DEB86}", "chu4E+zWwcwrWFpWkMcbhS1jwuE=", "Valtech.Foundation.Synthesis")]
    public partial interface ILinkItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Link Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_heading")]
        Synthesis.FieldTypes.Interfaces.ITextField LinkHeading {
            get;
        }
        
        /// <summary>Represents the Link Intro field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_intro")]
        Synthesis.FieldTypes.Interfaces.ITextField LinkIntro {
            get;
        }
        
        /// <summary>Represents the Link Target field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_target")]
        Synthesis.FieldTypes.Interfaces.IHyperlinkField LinkTarget {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/RichText template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{7A6E5726-35AD-4789-BE04-ED8575247C03}", "4cp66n1kmyYRX4EEgw9C7T1sRNc=", "Valtech.Foundation.Synthesis")]
    public partial interface IRichTextItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("text")]
        Synthesis.FieldTypes.Interfaces.IRichTextField Text {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Video template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{F717621B-4257-45DB-AECC-902A6F682FDB}", "tTxIj54zAqtGn7dLJb7OjNdyBa8=", "Valtech.Foundation.Synthesis")]
    public partial interface IVideoItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the YoutubeID field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("youtubeid")]
        Synthesis.FieldTypes.Interfaces.ITextField YoutubeID {
            get;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Concrete.Feature.ContentBlocks.Blocks {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndText template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class ImageAndText : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Blocks.IImageAndTextItem {
        
        private Synthesis.FieldTypes.TextField _heading1;
        
        private Synthesis.FieldTypes.ImageField _image1;
        
        private Synthesis.FieldTypes.RichTextField _text;
        
        private Synthesis.FieldTypes.BooleanField _invertPositions;
        
        public ImageAndText(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public ImageAndText(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "ImageAndText";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{21EA2408-A9D6-4CA6-AFD1-80798B77B5DB}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("heading")]
        public Synthesis.FieldTypes.Interfaces.ITextField Heading1 {
            get {
                if (_heading1 == null) {
                    _heading1 = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{172680EC-44BF-4CED-AAA6-DEC3A9E6CDC5}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndText", "Heading"), this.GetSearchFieldValue("heading"));
                }
                return _heading1;
            }
        }
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        public Synthesis.FieldTypes.Interfaces.IImageField Image1 {
            get {
                if (_image1 == null) {
                    _image1 = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{61F71B9B-9ED2-45A9-9003-B4A3D81056B4}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndText", "Image"), this.GetSearchFieldValue("image"));
                }
                return _image1;
            }
        }
        
        /// <summary>Represents the Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("text")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField Text {
            get {
                if (_text == null) {
                    _text = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2EA03F17-AA46-4522-839C-B02F90CE87AD}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndText", "Text"), this.GetSearchFieldValue("text"));
                }
                return _text;
            }
        }
        
        /// <summary>Represents the InvertPositions field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("invertpositions")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField InvertPositions {
            get {
                if (_invertPositions == null) {
                    _invertPositions = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2F4DFEFE-8EBC-4088-BE11-925B608FE2E4}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndText", "InvertPositions"), this.GetSearchFieldValue("invertpositions"));
                }
                return _invertPositions;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class ImageAndTextInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{21EA2408-A9D6-4CA6-AFD1-80798B77B5DB}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new ImageAndText(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new ImageAndText(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Blocks/Manual Link CTA template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class ManualLinkCTA : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Blocks.IManualLinkCTAItem {
        
        private Synthesis.FieldTypes.TextField _heading1;
        
        private Synthesis.FieldTypes.ImageField _image1;
        
        private Synthesis.FieldTypes.TextField _linkHeading;
        
        private Synthesis.FieldTypes.TextField _linkIntro;
        
        private Synthesis.FieldTypes.HyperlinkField _linkTarget;
        
        public ManualLinkCTA(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public ManualLinkCTA(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Manual Link CTA";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{AB4BCE34-FFF4-4045-AB94-6D05A7E95468}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("heading")]
        public Synthesis.FieldTypes.Interfaces.ITextField Heading1 {
            get {
                if (_heading1 == null) {
                    _heading1 = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{172680EC-44BF-4CED-AAA6-DEC3A9E6CDC5}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/Manual Link CTA", "Heading"), this.GetSearchFieldValue("heading"));
                }
                return _heading1;
            }
        }
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        public Synthesis.FieldTypes.Interfaces.IImageField Image1 {
            get {
                if (_image1 == null) {
                    _image1 = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{61F71B9B-9ED2-45A9-9003-B4A3D81056B4}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/Manual Link CTA", "Image"), this.GetSearchFieldValue("image"));
                }
                return _image1;
            }
        }
        
        /// <summary>Represents the Link Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_heading")]
        public Synthesis.FieldTypes.Interfaces.ITextField LinkHeading {
            get {
                if (_linkHeading == null) {
                    _linkHeading = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{231A37D9-1212-4904-9A3E-0886F4D694A6}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/Manual Link CTA", "Link Heading"), this.GetSearchFieldValue("link_heading"));
                }
                return _linkHeading;
            }
        }
        
        /// <summary>Represents the Link Intro field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_intro")]
        public Synthesis.FieldTypes.Interfaces.ITextField LinkIntro {
            get {
                if (_linkIntro == null) {
                    _linkIntro = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{AD86A76E-DA99-4B6E-B8E8-C44AAD2E6177}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/Manual Link CTA", "Link Intro"), this.GetSearchFieldValue("link_intro"));
                }
                return _linkIntro;
            }
        }
        
        /// <summary>Represents the Link Target field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_target")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField LinkTarget {
            get {
                if (_linkTarget == null) {
                    _linkTarget = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{784A2993-0FE3-4F65-8172-ABC04E6E8F7D}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/Manual Link CTA", "Link Target"), this.GetSearchFieldValue("link_target"));
                }
                return _linkTarget;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class ManualLinkCTAInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{AB4BCE34-FFF4-4045-AB94-6D05A7E95468}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new ManualLinkCTA(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new ManualLinkCTA(searchFields);
        }
    }
}
namespace FOS.Website.Concrete.Feature.ContentBlocks.Data {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Heading template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class Heading : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Data.IHeadingItem {
        
        private Synthesis.FieldTypes.TextField _heading1;
        
        public Heading(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Heading(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Heading";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{2F8D1730-8E48-4D2A-AC96-4547DD5CDC02}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("heading")]
        public Synthesis.FieldTypes.Interfaces.ITextField Heading1 {
            get {
                if (_heading1 == null) {
                    _heading1 = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{172680EC-44BF-4CED-AAA6-DEC3A9E6CDC5}"], "/sitecore/templates/Feature/ContentBlocks/Data/Heading", "Heading"), this.GetSearchFieldValue("heading"));
                }
                return _heading1;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class HeadingInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{2F8D1730-8E48-4D2A-AC96-4547DD5CDC02}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Heading(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Heading(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Image template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class Image : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Data.IImageItem {
        
        private Synthesis.FieldTypes.ImageField _image1;
        
        public Image(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Image(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Image";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{76F41557-F22A-4CFB-95E7-B3D9D1781FAC}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        public Synthesis.FieldTypes.Interfaces.IImageField Image1 {
            get {
                if (_image1 == null) {
                    _image1 = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{61F71B9B-9ED2-45A9-9003-B4A3D81056B4}"], "/sitecore/templates/Feature/ContentBlocks/Data/Image", "Image"), this.GetSearchFieldValue("image"));
                }
                return _image1;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class ImageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{76F41557-F22A-4CFB-95E7-B3D9D1781FAC}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Image(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Image(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Link template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class Link : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Data.ILinkItem {
        
        private Synthesis.FieldTypes.TextField _linkHeading;
        
        private Synthesis.FieldTypes.TextField _linkIntro;
        
        private Synthesis.FieldTypes.HyperlinkField _linkTarget;
        
        public Link(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Link(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Link";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{FA69C4B3-2B4A-4A48-89E7-8430DE6DEB86}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Link Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_heading")]
        public Synthesis.FieldTypes.Interfaces.ITextField LinkHeading {
            get {
                if (_linkHeading == null) {
                    _linkHeading = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{231A37D9-1212-4904-9A3E-0886F4D694A6}"], "/sitecore/templates/Feature/ContentBlocks/Data/Link", "Link Heading"), this.GetSearchFieldValue("link_heading"));
                }
                return _linkHeading;
            }
        }
        
        /// <summary>Represents the Link Intro field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_intro")]
        public Synthesis.FieldTypes.Interfaces.ITextField LinkIntro {
            get {
                if (_linkIntro == null) {
                    _linkIntro = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{AD86A76E-DA99-4B6E-B8E8-C44AAD2E6177}"], "/sitecore/templates/Feature/ContentBlocks/Data/Link", "Link Intro"), this.GetSearchFieldValue("link_intro"));
                }
                return _linkIntro;
            }
        }
        
        /// <summary>Represents the Link Target field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_target")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField LinkTarget {
            get {
                if (_linkTarget == null) {
                    _linkTarget = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{784A2993-0FE3-4F65-8172-ABC04E6E8F7D}"], "/sitecore/templates/Feature/ContentBlocks/Data/Link", "Link Target"), this.GetSearchFieldValue("link_target"));
                }
                return _linkTarget;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class LinkInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{FA69C4B3-2B4A-4A48-89E7-8430DE6DEB86}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Link(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Link(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/RichText template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class RichText : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Data.IRichTextItem {
        
        private Synthesis.FieldTypes.RichTextField _text;
        
        public RichText(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public RichText(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "RichText";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{7A6E5726-35AD-4789-BE04-ED8575247C03}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("text")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField Text {
            get {
                if (_text == null) {
                    _text = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2EA03F17-AA46-4522-839C-B02F90CE87AD}"], "/sitecore/templates/Feature/ContentBlocks/Data/RichText", "Text"), this.GetSearchFieldValue("text"));
                }
                return _text;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class RichTextInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{7A6E5726-35AD-4789-BE04-ED8575247C03}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new RichText(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new RichText(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Video template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class Video : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Data.IVideoItem {
        
        private Synthesis.FieldTypes.TextField _youtubeID;
        
        public Video(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Video(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Video";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{F717621B-4257-45DB-AECC-902A6F682FDB}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the YoutubeID field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("youtubeid")]
        public Synthesis.FieldTypes.Interfaces.ITextField YoutubeID {
            get {
                if (_youtubeID == null) {
                    _youtubeID = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{54D306E0-F243-4DBE-859D-248BBEC1A7D0}"], "/sitecore/templates/Feature/ContentBlocks/Data/Video", "YoutubeID"), this.GetSearchFieldValue("youtubeid"));
                }
                return _youtubeID;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class VideoInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{F717621B-4257-45DB-AECC-902A6F682FDB}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Video(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Video(searchFields);
        }
    }
}
