//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Feature.ContentBlocks.Blocks {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndText template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{21EA2408-A9D6-4CA6-AFD1-80798B77B5DB}", "rUpDfQXoMEoHrjPYOc6B5VBP76s=", "Valtech.Foundation.Synthesis")]
    public partial interface IImageAndTextItem : global::FOS.Website.Feature.ContentBlocks.Data.IHeadingItem, global::FOS.Website.Feature.ContentBlocks.Data.IImageItem, global::FOS.Website.Feature.ContentBlocks.Data.IRichTextItem, global::FOS.Website.Feature.ContentBlocks.Data.Settings.IInvertContentItem, global::FOS.Website.Feature.ContentBlocks.Data.Settings.IStyleItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndVideo template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{0D6361CF-8650-4D91-BFF1-13687D56C3E1}", "qOutfezjRhMy/uZ5FIsK2FDs+KE=", "Valtech.Foundation.Synthesis")]
    public partial interface IImageAndVideoItem : global::FOS.Website.Feature.ContentBlocks.Data.IHeadingItem {
        
        /// <summary>Represents the LeftVideo field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("leftvideo")]
        Synthesis.FieldTypes.Interfaces.ITextField LeftVideo {
            get;
        }
        
        /// <summary>Represents the LeftImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("leftimage")]
        Synthesis.FieldTypes.Interfaces.IImageField LeftImage {
            get;
        }
        
        /// <summary>Represents the RightVideo field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("rightvideo")]
        Synthesis.FieldTypes.Interfaces.ITextField RightVideo {
            get;
        }
        
        /// <summary>Represents the RightImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("rightimage")]
        Synthesis.FieldTypes.Interfaces.IImageField RightImage {
            get;
        }
        
        /// <summary>Represents the LeftVideoStartImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("leftvideostartimage")]
        Synthesis.FieldTypes.Interfaces.IImageField LeftVideoStartImage {
            get;
        }
        
        /// <summary>Represents the RightVideoStartImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("rightvideostartimage")]
        Synthesis.FieldTypes.Interfaces.IImageField RightVideoStartImage {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Blocks/Manual Link CTA template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{AB4BCE34-FFF4-4045-AB94-6D05A7E95468}", "KN1SMvNfluL4CXXZk51WM8Pa/PY=", "Valtech.Foundation.Synthesis")]
    public partial interface IManualLinkCTAItem : global::FOS.Website.Feature.ContentBlocks.Data.IHeadingItem, global::FOS.Website.Feature.ContentBlocks.Data.ILinkItem, global::FOS.Website.Feature.ContentBlocks.Data.IImageItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Blocks/VideoAndText template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{F7ECA36A-F814-44CD-B4BF-84D321220CCF}", "WbApP1baVRKGIDZDX34B2UB7eOY=", "Valtech.Foundation.Synthesis")]
    public partial interface IVideoAndTextItem : global::FOS.Website.Feature.ContentBlocks.Data.IHeadingItem, global::FOS.Website.Feature.ContentBlocks.Data.IRichTextItem, global::FOS.Website.Feature.ContentBlocks.Data.IVideoItem, global::FOS.Website.Feature.ContentBlocks.Data.Settings.IInvertContentItem, global::FOS.Website.Feature.ContentBlocks.Data.Settings.IStyleItem {
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Blocks/Wide Image Separator template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{AF5A8490-F600-4B4C-BC8B-B710461769BF}", "cMVvQGJKabw3aAU74fms9yXIY4g=", "Valtech.Foundation.Synthesis")]
    public partial interface IWideImageSeparatorItem : global::FOS.Website.Feature.ContentBlocks.Data.IHeadingItem, global::FOS.Website.Feature.ContentBlocks.Data.IImageItem, global::FOS.Website.Feature.ContentBlocks.Data.ISimpleTextBoxItem {
    }
}
namespace FOS.Website.Feature.ContentBlocks.Data {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Heading template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{2F8D1730-8E48-4D2A-AC96-4547DD5CDC02}", "FcOSvfGM2nzMXd1mzYjMV8wY/Sk=", "Valtech.Foundation.Synthesis")]
    public partial interface IHeadingItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("heading")]
        Synthesis.FieldTypes.Interfaces.ITextField Heading1 {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Image template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{76F41557-F22A-4CFB-95E7-B3D9D1781FAC}", "ANLZ27SJAlExNxsS2heCIgRQ5Og=", "Valtech.Foundation.Synthesis")]
    public partial interface IImageItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        Synthesis.FieldTypes.Interfaces.IImageField Image1 {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Link template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{FA69C4B3-2B4A-4A48-89E7-8430DE6DEB86}", "chu4E+zWwcwrWFpWkMcbhS1jwuE=", "Valtech.Foundation.Synthesis")]
    public partial interface ILinkItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Link Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_heading")]
        Synthesis.FieldTypes.Interfaces.ITextField LinkHeading {
            get;
        }
        
        /// <summary>Represents the Link Intro field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_intro")]
        Synthesis.FieldTypes.Interfaces.ITextField LinkIntro {
            get;
        }
        
        /// <summary>Represents the Link Target field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_target")]
        Synthesis.FieldTypes.Interfaces.IHyperlinkField LinkTarget {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/RichText template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{7A6E5726-35AD-4789-BE04-ED8575247C03}", "4cp66n1kmyYRX4EEgw9C7T1sRNc=", "Valtech.Foundation.Synthesis")]
    public partial interface IRichTextItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("text")]
        Synthesis.FieldTypes.Interfaces.IRichTextField Text {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/SimpleTextBox template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{6EC9DFC3-E55B-4057-9F88-CD17F5E144BC}", "nn4/wKl6Bx6VDo3ADSRCgcswzFk=", "Valtech.Foundation.Synthesis")]
    public partial interface ISimpleTextBoxItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Box Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("box_title")]
        Synthesis.FieldTypes.Interfaces.ITextField BoxTitle {
            get;
        }
        
        /// <summary>Represents the Paragraph field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("paragraph")]
        Synthesis.FieldTypes.Interfaces.ITextField Paragraph {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Video template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{F717621B-4257-45DB-AECC-902A6F682FDB}", "yz4qwZzmHcs9VZgJfoCTEmvTxfo=", "Valtech.Foundation.Synthesis")]
    public partial interface IVideoItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the YoutubeID field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("youtubeid")]
        Synthesis.FieldTypes.Interfaces.ITextField YoutubeID {
            get;
        }
        
        /// <summary>Represents the StartImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("startimage")]
        Synthesis.FieldTypes.Interfaces.IImageField StartImage {
            get;
        }
    }
}
namespace FOS.Website.Feature.ContentBlocks.Data.Settings {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Settings/InvertContent template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{045B2421-1361-42F0-8D39-DE0F1A9C6575}", "2mZAIdGmcV5dZ6TDuBVBY0IvR9o=", "Valtech.Foundation.Synthesis")]
    public partial interface IInvertContentItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the InvertPositions field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("invertpositions")]
        Synthesis.FieldTypes.Interfaces.IBooleanField InvertPositions {
            get;
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Settings/Style template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{49A5DB17-079B-47C1-9F1B-101E72006B3A}", "0gJ94H6JRkwmkg3RaKvq0dxvgog=", "Valtech.Foundation.Synthesis")]
    public partial interface IStyleItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the Style field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("style")]
        Synthesis.FieldTypes.Interfaces.IItemReferenceField Style1 {
            get;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Concrete.Feature.ContentBlocks.Blocks {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndText template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class ImageAndText : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Blocks.IImageAndTextItem {
        
        private Synthesis.FieldTypes.TextField _heading1;
        
        private Synthesis.FieldTypes.ImageField _image1;
        
        private Synthesis.FieldTypes.RichTextField _text;
        
        private Synthesis.FieldTypes.BooleanField _invertPositions;
        
        private Synthesis.FieldTypes.ItemReferenceField _style1;
        
        public ImageAndText(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public ImageAndText(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "ImageAndText";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{21EA2408-A9D6-4CA6-AFD1-80798B77B5DB}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("heading")]
        public Synthesis.FieldTypes.Interfaces.ITextField Heading1 {
            get {
                if (_heading1 == null) {
                    _heading1 = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{172680EC-44BF-4CED-AAA6-DEC3A9E6CDC5}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndText", "Heading"), this.GetSearchFieldValue("heading"));
                }
                return _heading1;
            }
        }
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        public Synthesis.FieldTypes.Interfaces.IImageField Image1 {
            get {
                if (_image1 == null) {
                    _image1 = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{61F71B9B-9ED2-45A9-9003-B4A3D81056B4}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndText", "Image"), this.GetSearchFieldValue("image"));
                }
                return _image1;
            }
        }
        
        /// <summary>Represents the Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("text")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField Text {
            get {
                if (_text == null) {
                    _text = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2EA03F17-AA46-4522-839C-B02F90CE87AD}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndText", "Text"), this.GetSearchFieldValue("text"));
                }
                return _text;
            }
        }
        
        /// <summary>Represents the InvertPositions field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("invertpositions")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField InvertPositions {
            get {
                if (_invertPositions == null) {
                    _invertPositions = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2F4DFEFE-8EBC-4088-BE11-925B608FE2E4}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndText", "InvertPositions"), this.GetSearchFieldValue("invertpositions"));
                }
                return _invertPositions;
            }
        }
        
        /// <summary>Represents the Style field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("style")]
        public Synthesis.FieldTypes.Interfaces.IItemReferenceField Style1 {
            get {
                if (_style1 == null) {
                    _style1 = new Synthesis.FieldTypes.ItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{29F6CD5C-6EC6-4D39-99EA-35A1F6567BB8}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndText", "Style"), this.GetSearchFieldValue("style"));
                }
                return _style1;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class ImageAndTextInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{21EA2408-A9D6-4CA6-AFD1-80798B77B5DB}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new ImageAndText(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new ImageAndText(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndVideo template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class ImageAndVideo : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Blocks.IImageAndVideoItem {
        
        private Synthesis.FieldTypes.TextField _heading1;
        
        private Synthesis.FieldTypes.TextField _leftVideo;
        
        private Synthesis.FieldTypes.ImageField _leftImage;
        
        private Synthesis.FieldTypes.TextField _rightVideo;
        
        private Synthesis.FieldTypes.ImageField _rightImage;
        
        private Synthesis.FieldTypes.ImageField _leftVideoStartImage;
        
        private Synthesis.FieldTypes.ImageField _rightVideoStartImage;
        
        public ImageAndVideo(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public ImageAndVideo(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "ImageAndVideo";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{0D6361CF-8650-4D91-BFF1-13687D56C3E1}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("heading")]
        public Synthesis.FieldTypes.Interfaces.ITextField Heading1 {
            get {
                if (_heading1 == null) {
                    _heading1 = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{172680EC-44BF-4CED-AAA6-DEC3A9E6CDC5}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndVideo", "Heading"), this.GetSearchFieldValue("heading"));
                }
                return _heading1;
            }
        }
        
        /// <summary>Represents the LeftVideo field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("leftvideo")]
        public Synthesis.FieldTypes.Interfaces.ITextField LeftVideo {
            get {
                if (_leftVideo == null) {
                    _leftVideo = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{6467C812-37A4-455C-B6FF-4364AE5CECAF}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndVideo", "LeftVideo"), this.GetSearchFieldValue("leftvideo"));
                }
                return _leftVideo;
            }
        }
        
        /// <summary>Represents the LeftImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("leftimage")]
        public Synthesis.FieldTypes.Interfaces.IImageField LeftImage {
            get {
                if (_leftImage == null) {
                    _leftImage = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{E5C16C8F-F6BA-4861-8735-F1C5FC6C577D}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndVideo", "LeftImage"), this.GetSearchFieldValue("leftimage"));
                }
                return _leftImage;
            }
        }
        
        /// <summary>Represents the RightVideo field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("rightvideo")]
        public Synthesis.FieldTypes.Interfaces.ITextField RightVideo {
            get {
                if (_rightVideo == null) {
                    _rightVideo = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{6CD27145-CFB6-45BA-AFA1-69DDA0037E98}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndVideo", "RightVideo"), this.GetSearchFieldValue("rightvideo"));
                }
                return _rightVideo;
            }
        }
        
        /// <summary>Represents the RightImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("rightimage")]
        public Synthesis.FieldTypes.Interfaces.IImageField RightImage {
            get {
                if (_rightImage == null) {
                    _rightImage = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{118EA6FC-046A-41A9-A0E9-9A948FF1A33A}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndVideo", "RightImage"), this.GetSearchFieldValue("rightimage"));
                }
                return _rightImage;
            }
        }
        
        /// <summary>Represents the LeftVideoStartImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("leftvideostartimage")]
        public Synthesis.FieldTypes.Interfaces.IImageField LeftVideoStartImage {
            get {
                if (_leftVideoStartImage == null) {
                    _leftVideoStartImage = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{BE7C7F7D-5DCE-4689-9CEB-33033C29DA06}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndVideo", "LeftVideoStartImage"), this.GetSearchFieldValue("leftvideostartimage"));
                }
                return _leftVideoStartImage;
            }
        }
        
        /// <summary>Represents the RightVideoStartImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("rightvideostartimage")]
        public Synthesis.FieldTypes.Interfaces.IImageField RightVideoStartImage {
            get {
                if (_rightVideoStartImage == null) {
                    _rightVideoStartImage = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{70229C36-FE4E-4CEA-8ADF-0E241450ECBA}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/ImageAndVideo", "RightVideoStartImage"), this.GetSearchFieldValue("rightvideostartimage"));
                }
                return _rightVideoStartImage;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class ImageAndVideoInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{0D6361CF-8650-4D91-BFF1-13687D56C3E1}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new ImageAndVideo(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new ImageAndVideo(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Blocks/Manual Link CTA template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class ManualLinkCTA : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Blocks.IManualLinkCTAItem {
        
        private Synthesis.FieldTypes.TextField _heading1;
        
        private Synthesis.FieldTypes.ImageField _image1;
        
        private Synthesis.FieldTypes.TextField _linkHeading;
        
        private Synthesis.FieldTypes.TextField _linkIntro;
        
        private Synthesis.FieldTypes.HyperlinkField _linkTarget;
        
        public ManualLinkCTA(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public ManualLinkCTA(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Manual Link CTA";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{AB4BCE34-FFF4-4045-AB94-6D05A7E95468}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("heading")]
        public Synthesis.FieldTypes.Interfaces.ITextField Heading1 {
            get {
                if (_heading1 == null) {
                    _heading1 = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{172680EC-44BF-4CED-AAA6-DEC3A9E6CDC5}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/Manual Link CTA", "Heading"), this.GetSearchFieldValue("heading"));
                }
                return _heading1;
            }
        }
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        public Synthesis.FieldTypes.Interfaces.IImageField Image1 {
            get {
                if (_image1 == null) {
                    _image1 = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{61F71B9B-9ED2-45A9-9003-B4A3D81056B4}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/Manual Link CTA", "Image"), this.GetSearchFieldValue("image"));
                }
                return _image1;
            }
        }
        
        /// <summary>Represents the Link Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_heading")]
        public Synthesis.FieldTypes.Interfaces.ITextField LinkHeading {
            get {
                if (_linkHeading == null) {
                    _linkHeading = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{231A37D9-1212-4904-9A3E-0886F4D694A6}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/Manual Link CTA", "Link Heading"), this.GetSearchFieldValue("link_heading"));
                }
                return _linkHeading;
            }
        }
        
        /// <summary>Represents the Link Intro field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_intro")]
        public Synthesis.FieldTypes.Interfaces.ITextField LinkIntro {
            get {
                if (_linkIntro == null) {
                    _linkIntro = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{AD86A76E-DA99-4B6E-B8E8-C44AAD2E6177}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/Manual Link CTA", "Link Intro"), this.GetSearchFieldValue("link_intro"));
                }
                return _linkIntro;
            }
        }
        
        /// <summary>Represents the Link Target field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_target")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField LinkTarget {
            get {
                if (_linkTarget == null) {
                    _linkTarget = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{784A2993-0FE3-4F65-8172-ABC04E6E8F7D}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/Manual Link CTA", "Link Target"), this.GetSearchFieldValue("link_target"));
                }
                return _linkTarget;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class ManualLinkCTAInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{AB4BCE34-FFF4-4045-AB94-6D05A7E95468}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new ManualLinkCTA(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new ManualLinkCTA(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Blocks/VideoAndText template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class VideoAndText : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Blocks.IVideoAndTextItem {
        
        private Synthesis.FieldTypes.TextField _heading1;
        
        private Synthesis.FieldTypes.RichTextField _text;
        
        private Synthesis.FieldTypes.TextField _youtubeID;
        
        private Synthesis.FieldTypes.ImageField _startImage;
        
        private Synthesis.FieldTypes.BooleanField _invertPositions;
        
        private Synthesis.FieldTypes.ItemReferenceField _style1;
        
        public VideoAndText(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public VideoAndText(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "VideoAndText";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{F7ECA36A-F814-44CD-B4BF-84D321220CCF}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("heading")]
        public Synthesis.FieldTypes.Interfaces.ITextField Heading1 {
            get {
                if (_heading1 == null) {
                    _heading1 = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{172680EC-44BF-4CED-AAA6-DEC3A9E6CDC5}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/VideoAndText", "Heading"), this.GetSearchFieldValue("heading"));
                }
                return _heading1;
            }
        }
        
        /// <summary>Represents the Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("text")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField Text {
            get {
                if (_text == null) {
                    _text = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2EA03F17-AA46-4522-839C-B02F90CE87AD}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/VideoAndText", "Text"), this.GetSearchFieldValue("text"));
                }
                return _text;
            }
        }
        
        /// <summary>Represents the YoutubeID field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("youtubeid")]
        public Synthesis.FieldTypes.Interfaces.ITextField YoutubeID {
            get {
                if (_youtubeID == null) {
                    _youtubeID = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{54D306E0-F243-4DBE-859D-248BBEC1A7D0}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/VideoAndText", "YoutubeID"), this.GetSearchFieldValue("youtubeid"));
                }
                return _youtubeID;
            }
        }
        
        /// <summary>Represents the StartImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("startimage")]
        public Synthesis.FieldTypes.Interfaces.IImageField StartImage {
            get {
                if (_startImage == null) {
                    _startImage = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2E6D32D7-E51D-495A-B71D-C1685CAD857B}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/VideoAndText", "StartImage"), this.GetSearchFieldValue("startimage"));
                }
                return _startImage;
            }
        }
        
        /// <summary>Represents the InvertPositions field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("invertpositions")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField InvertPositions {
            get {
                if (_invertPositions == null) {
                    _invertPositions = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2F4DFEFE-8EBC-4088-BE11-925B608FE2E4}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/VideoAndText", "InvertPositions"), this.GetSearchFieldValue("invertpositions"));
                }
                return _invertPositions;
            }
        }
        
        /// <summary>Represents the Style field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("style")]
        public Synthesis.FieldTypes.Interfaces.IItemReferenceField Style1 {
            get {
                if (_style1 == null) {
                    _style1 = new Synthesis.FieldTypes.ItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{29F6CD5C-6EC6-4D39-99EA-35A1F6567BB8}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/VideoAndText", "Style"), this.GetSearchFieldValue("style"));
                }
                return _style1;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class VideoAndTextInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{F7ECA36A-F814-44CD-B4BF-84D321220CCF}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new VideoAndText(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new VideoAndText(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Blocks/Wide Image Separator template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class WideImageSeparator : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Blocks.IWideImageSeparatorItem {
        
        private Synthesis.FieldTypes.TextField _boxTitle;
        
        private Synthesis.FieldTypes.TextField _heading1;
        
        private Synthesis.FieldTypes.ImageField _image1;
        
        private Synthesis.FieldTypes.TextField _paragraph;
        
        public WideImageSeparator(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public WideImageSeparator(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Wide Image Separator";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{AF5A8490-F600-4B4C-BC8B-B710461769BF}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Box Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("box_title")]
        public Synthesis.FieldTypes.Interfaces.ITextField BoxTitle {
            get {
                if (_boxTitle == null) {
                    _boxTitle = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{9425421A-3417-42D7-B998-9D263E8268C9}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/Wide Image Separator", "Box Title"), this.GetSearchFieldValue("box_title"));
                }
                return _boxTitle;
            }
        }
        
        /// <summary>Represents the Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("heading")]
        public Synthesis.FieldTypes.Interfaces.ITextField Heading1 {
            get {
                if (_heading1 == null) {
                    _heading1 = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{172680EC-44BF-4CED-AAA6-DEC3A9E6CDC5}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/Wide Image Separator", "Heading"), this.GetSearchFieldValue("heading"));
                }
                return _heading1;
            }
        }
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        public Synthesis.FieldTypes.Interfaces.IImageField Image1 {
            get {
                if (_image1 == null) {
                    _image1 = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{61F71B9B-9ED2-45A9-9003-B4A3D81056B4}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/Wide Image Separator", "Image"), this.GetSearchFieldValue("image"));
                }
                return _image1;
            }
        }
        
        /// <summary>Represents the Paragraph field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("paragraph")]
        public Synthesis.FieldTypes.Interfaces.ITextField Paragraph {
            get {
                if (_paragraph == null) {
                    _paragraph = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{A8164555-F140-4305-B722-1CA52DFA5780}"], "/sitecore/templates/Feature/ContentBlocks/Blocks/Wide Image Separator", "Paragraph"), this.GetSearchFieldValue("paragraph"));
                }
                return _paragraph;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class WideImageSeparatorInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{AF5A8490-F600-4B4C-BC8B-B710461769BF}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new WideImageSeparator(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new WideImageSeparator(searchFields);
        }
    }
}
namespace FOS.Website.Concrete.Feature.ContentBlocks.Data {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Heading template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class Heading : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Data.IHeadingItem {
        
        private Synthesis.FieldTypes.TextField _heading1;
        
        public Heading(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Heading(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Heading";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{2F8D1730-8E48-4D2A-AC96-4547DD5CDC02}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("heading")]
        public Synthesis.FieldTypes.Interfaces.ITextField Heading1 {
            get {
                if (_heading1 == null) {
                    _heading1 = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{172680EC-44BF-4CED-AAA6-DEC3A9E6CDC5}"], "/sitecore/templates/Feature/ContentBlocks/Data/Heading", "Heading"), this.GetSearchFieldValue("heading"));
                }
                return _heading1;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class HeadingInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{2F8D1730-8E48-4D2A-AC96-4547DD5CDC02}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Heading(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Heading(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Image template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class Image : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Data.IImageItem {
        
        private Synthesis.FieldTypes.ImageField _image1;
        
        public Image(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Image(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Image";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{76F41557-F22A-4CFB-95E7-B3D9D1781FAC}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Image field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("image")]
        public Synthesis.FieldTypes.Interfaces.IImageField Image1 {
            get {
                if (_image1 == null) {
                    _image1 = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{61F71B9B-9ED2-45A9-9003-B4A3D81056B4}"], "/sitecore/templates/Feature/ContentBlocks/Data/Image", "Image"), this.GetSearchFieldValue("image"));
                }
                return _image1;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class ImageInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{76F41557-F22A-4CFB-95E7-B3D9D1781FAC}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Image(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Image(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Link template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class Link : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Data.ILinkItem {
        
        private Synthesis.FieldTypes.TextField _linkHeading;
        
        private Synthesis.FieldTypes.TextField _linkIntro;
        
        private Synthesis.FieldTypes.HyperlinkField _linkTarget;
        
        public Link(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Link(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Link";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{FA69C4B3-2B4A-4A48-89E7-8430DE6DEB86}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Link Heading field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_heading")]
        public Synthesis.FieldTypes.Interfaces.ITextField LinkHeading {
            get {
                if (_linkHeading == null) {
                    _linkHeading = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{231A37D9-1212-4904-9A3E-0886F4D694A6}"], "/sitecore/templates/Feature/ContentBlocks/Data/Link", "Link Heading"), this.GetSearchFieldValue("link_heading"));
                }
                return _linkHeading;
            }
        }
        
        /// <summary>Represents the Link Intro field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_intro")]
        public Synthesis.FieldTypes.Interfaces.ITextField LinkIntro {
            get {
                if (_linkIntro == null) {
                    _linkIntro = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{AD86A76E-DA99-4B6E-B8E8-C44AAD2E6177}"], "/sitecore/templates/Feature/ContentBlocks/Data/Link", "Link Intro"), this.GetSearchFieldValue("link_intro"));
                }
                return _linkIntro;
            }
        }
        
        /// <summary>Represents the Link Target field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("link_target")]
        public Synthesis.FieldTypes.Interfaces.IHyperlinkField LinkTarget {
            get {
                if (_linkTarget == null) {
                    _linkTarget = new Synthesis.FieldTypes.HyperlinkField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{784A2993-0FE3-4F65-8172-ABC04E6E8F7D}"], "/sitecore/templates/Feature/ContentBlocks/Data/Link", "Link Target"), this.GetSearchFieldValue("link_target"));
                }
                return _linkTarget;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class LinkInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{FA69C4B3-2B4A-4A48-89E7-8430DE6DEB86}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Link(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Link(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/RichText template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class RichText : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Data.IRichTextItem {
        
        private Synthesis.FieldTypes.RichTextField _text;
        
        public RichText(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public RichText(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "RichText";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{7A6E5726-35AD-4789-BE04-ED8575247C03}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Text field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("text")]
        public Synthesis.FieldTypes.Interfaces.IRichTextField Text {
            get {
                if (_text == null) {
                    _text = new Synthesis.FieldTypes.RichTextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2EA03F17-AA46-4522-839C-B02F90CE87AD}"], "/sitecore/templates/Feature/ContentBlocks/Data/RichText", "Text"), this.GetSearchFieldValue("text"));
                }
                return _text;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class RichTextInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{7A6E5726-35AD-4789-BE04-ED8575247C03}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new RichText(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new RichText(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/SimpleTextBox template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class SimpleTextBox : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Data.ISimpleTextBoxItem {
        
        private Synthesis.FieldTypes.TextField _boxTitle;
        
        private Synthesis.FieldTypes.TextField _paragraph;
        
        public SimpleTextBox(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public SimpleTextBox(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "SimpleTextBox";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{6EC9DFC3-E55B-4057-9F88-CD17F5E144BC}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Box Title field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("box_title")]
        public Synthesis.FieldTypes.Interfaces.ITextField BoxTitle {
            get {
                if (_boxTitle == null) {
                    _boxTitle = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{9425421A-3417-42D7-B998-9D263E8268C9}"], "/sitecore/templates/Feature/ContentBlocks/Data/SimpleTextBox", "Box Title"), this.GetSearchFieldValue("box_title"));
                }
                return _boxTitle;
            }
        }
        
        /// <summary>Represents the Paragraph field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("paragraph")]
        public Synthesis.FieldTypes.Interfaces.ITextField Paragraph {
            get {
                if (_paragraph == null) {
                    _paragraph = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{A8164555-F140-4305-B722-1CA52DFA5780}"], "/sitecore/templates/Feature/ContentBlocks/Data/SimpleTextBox", "Paragraph"), this.GetSearchFieldValue("paragraph"));
                }
                return _paragraph;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class SimpleTextBoxInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{6EC9DFC3-E55B-4057-9F88-CD17F5E144BC}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new SimpleTextBox(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new SimpleTextBox(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Video template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class Video : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Data.IVideoItem {
        
        private Synthesis.FieldTypes.TextField _youtubeID;
        
        private Synthesis.FieldTypes.ImageField _startImage;
        
        public Video(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Video(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Video";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{F717621B-4257-45DB-AECC-902A6F682FDB}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the YoutubeID field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("youtubeid")]
        public Synthesis.FieldTypes.Interfaces.ITextField YoutubeID {
            get {
                if (_youtubeID == null) {
                    _youtubeID = new Synthesis.FieldTypes.TextField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{54D306E0-F243-4DBE-859D-248BBEC1A7D0}"], "/sitecore/templates/Feature/ContentBlocks/Data/Video", "YoutubeID"), this.GetSearchFieldValue("youtubeid"));
                }
                return _youtubeID;
            }
        }
        
        /// <summary>Represents the StartImage field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("startimage")]
        public Synthesis.FieldTypes.Interfaces.IImageField StartImage {
            get {
                if (_startImage == null) {
                    _startImage = new Synthesis.FieldTypes.ImageField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2E6D32D7-E51D-495A-B71D-C1685CAD857B}"], "/sitecore/templates/Feature/ContentBlocks/Data/Video", "StartImage"), this.GetSearchFieldValue("startimage"));
                }
                return _startImage;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class VideoInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{F717621B-4257-45DB-AECC-902A6F682FDB}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Video(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Video(searchFields);
        }
    }
}
namespace FOS.Website.Concrete.Feature.ContentBlocks.Data.Settings {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Settings/InvertContent template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class InvertContent : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Data.Settings.IInvertContentItem {
        
        private Synthesis.FieldTypes.BooleanField _invertPositions;
        
        public InvertContent(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public InvertContent(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "InvertContent";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{045B2421-1361-42F0-8D39-DE0F1A9C6575}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the InvertPositions field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("invertpositions")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField InvertPositions {
            get {
                if (_invertPositions == null) {
                    _invertPositions = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{2F4DFEFE-8EBC-4088-BE11-925B608FE2E4}"], "/sitecore/templates/Feature/ContentBlocks/Data/Settings/InvertContent", "InvertPositions"), this.GetSearchFieldValue("invertpositions"));
                }
                return _invertPositions;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class InvertContentInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{045B2421-1361-42F0-8D39-DE0F1A9C6575}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new InvertContent(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new InvertContent(searchFields);
        }
    }
    
    /// <summary>Represents the /sitecore/templates/Feature/ContentBlocks/Data/Settings/Style template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class Style : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.ContentBlocks.Data.Settings.IStyleItem {
        
        private Synthesis.FieldTypes.ItemReferenceField _style1;
        
        public Style(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public Style(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "Style";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{49A5DB17-079B-47C1-9F1B-101E72006B3A}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the Style field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("style")]
        public Synthesis.FieldTypes.Interfaces.IItemReferenceField Style1 {
            get {
                if (_style1 == null) {
                    _style1 = new Synthesis.FieldTypes.ItemReferenceField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{29F6CD5C-6EC6-4D39-99EA-35A1F6567BB8}"], "/sitecore/templates/Feature/ContentBlocks/Data/Settings/Style", "Style"), this.GetSearchFieldValue("style"));
                }
                return _style1;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class StyleInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{49A5DB17-079B-47C1-9F1B-101E72006B3A}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new Style(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new Style(searchFields);
        }
    }
}
