//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Feature.News {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/News/News template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    [Synthesis.Synchronization.RepresentsSitecoreTemplateAttribute("{A0FACC8C-ADB9-40D7-893A-7036BF4D68CD}", "jEv5PVjfMwPhLC3ZAmTeQWY8x7Y=", "Valtech.Foundation.Synthesis")]
    public partial interface INewsItem : Synthesis.IStandardTemplateItem {
        
        /// <summary>Represents the NewsDate field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("newsdate")]
        Synthesis.FieldTypes.Interfaces.IDateTimeField NewsDate {
            get;
        }
        
        /// <summary>Represents the DisableDate field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("disabledate")]
        Synthesis.FieldTypes.Interfaces.IBooleanField DisableDate {
            get;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.Website.Concrete.Feature.News {
    
    
    /// <summary>Represents the /sitecore/templates/Feature/News/News template</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public partial class News : global::Synthesis.StandardTemplateItem, global::FOS.Website.Feature.News.INewsItem {
        
        private Synthesis.FieldTypes.DateTimeField _newsDate;
        
        private Synthesis.FieldTypes.BooleanField _disableDate;
        
        public News(Sitecore.Data.Items.Item innerItem) : 
                base(innerItem) {
        }
        
        public News(global::System.Collections.Generic.IDictionary<string, string> searchFields) : 
                base(searchFields) {
        }
        
        /// <summary>The name of the Sitecore Template that this class represents</summary>
        public static string TemplateName {
            get {
                return "News";
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public static Sitecore.Data.ID ItemTemplateId {
            get {
                return new Sitecore.Data.ID("{A0FACC8C-ADB9-40D7-893A-7036BF4D68CD}");
            }
        }
        
        /// <summary>The ID of the Sitecore Template that this class represents</summary>
        public override Sitecore.Data.ID TemplateId {
            get {
                return ItemTemplateId;
            }
        }
        
        /// <summary>Represents the NewsDate field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("newsdate")]
        public Synthesis.FieldTypes.Interfaces.IDateTimeField NewsDate {
            get {
                if (_newsDate == null) {
                    _newsDate = new Synthesis.FieldTypes.DateTimeField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{9FE23315-357A-4BE1-93B9-67E2A4E58368}"], "/sitecore/templates/Feature/News/News", "NewsDate"), this.GetSearchFieldValue("newsdate"));
                }
                return _newsDate;
            }
        }
        
        /// <summary>Represents the DisableDate field</summary>
        [Sitecore.ContentSearch.IndexFieldAttribute("disabledate")]
        public Synthesis.FieldTypes.Interfaces.IBooleanField DisableDate {
            get {
                if (_disableDate == null) {
                    _disableDate = new Synthesis.FieldTypes.BooleanField(new global::Synthesis.FieldTypes.LazyField(() => InnerItem.Fields["{93208228-3AEF-466C-A19B-CD9EA1EA5774}"], "/sitecore/templates/Feature/News/News", "DisableDate"), this.GetSearchFieldValue("disabledate"));
                }
                return _disableDate;
            }
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Synthesis", "8.2")]
    public class NewsInitializer : Synthesis.Initializers.ITemplateInitializer {
        
        public Sitecore.Data.ID InitializesTemplateId {
            get {
                return new Sitecore.Data.ID("{A0FACC8C-ADB9-40D7-893A-7036BF4D68CD}");
            }
        }
        
        public Synthesis.IStandardTemplateItem CreateInstance(Sitecore.Data.Items.Item innerItem) {
            return new News(innerItem);
        }
        
        public Synthesis.IStandardTemplateItem CreateInstanceFromSearch(global::System.Collections.Generic.IDictionary<string, string> searchFields) {
            return new News(searchFields);
        }
    }
}
